import { SCHEME_FORM_TE } from '@/lib/individualDpr/schemeFormTe';
import { SCHEME_STEP_TITLES_TE } from '@/lib/individualDpr/schemeStepTitlesTe';
import { BUSINESS_SKILLS_TE } from '@/lib/individualDpr/businessSkillsTe';
import { FORM_FIELD_TE } from '@/lib/individualDpr/formFieldTe';
import { AP_PLACES_TE } from '@/lib/individualDpr/apPlacesTe';
import { useTranslation } from 'react-i18next';
import { useCallback } from 'react';

/** English UI string → Telugu. Missing keys fall back to English. */
const TE: Record<string, string> = {
  ...SCHEME_FORM_TE,
  ...SCHEME_STEP_TITLES_TE,
  ...BUSINESS_SKILLS_TE,
  ...FORM_FIELD_TE,
  ...AP_PLACES_TE,
  'Cluster Name *': 'క్లస్టర్ పేరు *',
  'District *': 'జిల్లా *',
  'Location *': 'స్థలం *',
  'Geographical Spread': 'భౌగోళిక విస్తరణ',
  'Nature of Business': 'వ్యాపార స్వభావం',
  'Major Products': 'ప్రధాన ఉత్పత్తులు',
  'Enterprise Count': 'ఎంటర్‌ప్రైజ్‌ల సంఖ్య',
  Micro: 'మైక్రో',
  Small: 'చిన్న',
  Medium: 'మధ్యస్థ',
  'Age of Enterprises': 'ఎంటర్‌ప్రైజ్‌ల వయసు',
  '< 5 years': '5 సంవత్సరాల లోపు',
  '5-10 years': '5-10 సంవత్సరాలు',
  '> 10 years': '10 సంవత్సరాలు పైన',
  'Employment per Unit': 'యూనిట్‌కు ఉపాధి',
  '< 5 employees': '5 మంది లోపు',
  '5-10 employees': '5-10 మంది',
  '> 10 employees': '10 మంది పైన',
  'Investment per Unit (₹ Lakhs)': 'యూనిట్‌కు పెట్టుబడి (₹ లక్షలు)',
  'Turnover per Unit (₹ Lakhs)': 'యూనిట్‌కు టర్నోవర్ (₹ లక్షలు)',
  'Market Served (%)': 'సేవ చేసే మార్కెట్ (%)',
  Domestic: 'దేశీయ',
  Export: 'ఎగుమతి',
  'Sector / Industry Type': 'రంగం / పరిశ్రమ రకం',
  'Sector Description': 'రంగం వివరణ',
  'National Importance': 'జాతీయ ప్రాముఖ్యత',
  'State-level Importance': 'రాష్ట్ర స్థాయి ప్రాముఖ్యత',
  'Key Products': 'ప్రధాన ఉత్పత్తులు',
  'Add Product': 'ఉత్పత్తి జోడించండి',
  Geography: 'భౌగోళికం',
  Climate: 'వాతావరణం',
  Infrastructure: 'మౌలిక సదుపాయాలు',
  'Key Economic Activities': 'ప్రధాన ఆర్థిక కార్యకలాపాలు',
  'Raw Material Availability': 'ముడి పదార్థాల లభ్యత',
  'Raw Material Quantity': 'ముడి పదార్థాల పరిమాణం',
  'Industrial Infrastructure': 'పారిశ్రామిక మౌలిక సదుపాయాలు',
  Connectivity: 'కనెక్టివిటీ',
  Road: 'రోడ్డు',
  Rail: 'రైలు',
  Port: 'పోర్టు',
  'Year of Establishment': 'స్థాపన సంవత్సరం',
  'Cluster Evolution': 'క్లస్టర్ పరిణామం',
  'Present Activities': 'ప్రస్తుత కార్యకలాపాలు',
  'Type of Units': 'యూనిట్ల రకం',
  'Production Capacity': 'ఉత్పత్తి సామర్థ్యం',
  'Technology Level': 'సాంకేతిక స్థాయి',
  Stakeholders: 'వాటాదారులు',
  'Raw Materials': 'ముడి పదార్థాలు',
  'Add Raw Material': 'ముడి పదార్థం జోడించండి',
  'Intermediate Products': 'మధ్యంతర ఉత్పత్తులు',
  'Final Products': 'తుది ఉత్పత్తులు',
  'Add Final Product': 'తుది ఉత్పత్తి జోడించండి',
  'Value Addition Stages': 'విలువ జోడింపు దశలు',
  'Add Value Addition Stage': 'విలువ జోడింపు దశను జోడించండి',
  'Major Buyers': 'ప్రధాన కొనుగోలుదారులు',
  'Existing Demand': 'ప్రస్తుత డిమాండ్',
  'Demand-Supply Gap': 'డిమాండ్-సప్లై అంతరం',
  'Target Market': 'లక్ష్య మార్కెట్',
  'Competitor Analysis': 'పోటీ విశ్లేషణ',
  'Price Trends': 'ధరల ధోరణులు',
  'Export Potential': 'ఎగుమతి సామర్థ్యం',
  'Technology Gaps': 'సాంకేతిక అంతరాలు',
  'Infrastructure Gaps': 'మౌలిక సదుపాయాల అంతరాలు',
  'Skill Gaps': 'నైపుణ్య అంతరాలు',
  'Marketing Gaps': 'మార్కెటింగ్ అంతరాలు',
  'Financial Gaps': 'ఆర్థిక అంతరాలు',
  'Justification for Intervention': 'జోక్యానికి సమర్థన',
  Strengths: 'బలాలు',
  Weaknesses: 'బలహీనతలు',
  Opportunities: 'అవకాశాలు',
  Threats: 'ముప్పులు',
  'Intervention Type': 'జోక్యం రకం',
  'Select type': 'రకం ఎంచుకోండి',
  Hard: 'హార్డ్',
  Soft: 'సాఫ్ట్',
  Both: 'రెండూ',
  Description: 'వివరణ',
  Objectives: 'లక్ష్యాలు',
  'Add Objective': 'లక్ష్యం జోడించండి',
  'Expected Benefits': 'ఆశించిన ప్రయోజనాలు',
  Name: 'పేరు',
  Location: 'స్థలం',
  'Land Details': 'భూమి వివరాలు',
  'Civil Works': 'సివిల్ పనులు',
  'Manufacturing Process': 'తయారీ ప్రక్రియ',
  'Plant & Machinery': 'ప్లాంట్ మరియు యంత్రాలు',
  Capacity: 'సామర్థ్యం',
  'Power Requirements': 'విద్యుత్ అవసరాలు',
  'Water Requirements': 'నీటి అవసరాలు',
  'Manpower Requirements': 'మానవశక్తి అవసరాలు',
  'SPV Name': 'SPV పేరు',
  'Legal Status': 'చట్టపరమైన స్థితి',
  'Year of Incorporation': 'నమోదు సంవత్సరం',
  'Submitted To': 'సమర్పించిన సంస్థ',
  'Roles & Responsibilities': 'పాత్రలు మరియు బాధ్యతలు',
  'Board of Directors': 'డైరెక్టర్ల బోర్డు',
  'Add Director': 'డైరెక్టర్ జోడించండి',
  'Shareholding Pattern': 'వాటా నమూనా',
  'Add Shareholder': 'వాటాదారుని జోడించండి',
  'Member Units': 'సభ్య యూనిట్లు',
  'Add Member Unit': 'సభ్య యూనిట్ జోడించండి',
  'Statutory Registrations': 'చట్టబద్ధమైన నమోదులు',
  'Land (₹ Lakhs)': 'భూమి (₹ లక్షలు)',
  'Building (₹ Lakhs)': 'భవనం (₹ లక్షలు)',
  'Machinery (₹ Lakhs)': 'యంత్రాలు (₹ లక్షలు)',
  'Utilities & Infrastructure (₹ Lakhs)': 'యుటిలిటీలు & మౌలిక సదుపాయాలు (₹ లక్షలు)',
  'Preliminary & Pre-operative (₹ Lakhs)': 'ప్రాథమిక & ప్రీ-ఆపరేటివ్ (₹ లక్షలు)',
  'Working Capital Margin (₹ Lakhs)': 'వర్కింగ్ క్యాపిటల్ మార్జిన్ (₹ లక్షలు)',
  'Total Project Cost': 'మొత్తం ప్రాజెక్ట్ ఖర్చు',
  Lakhs: 'లక్షలు',
  'SPV Contribution (₹ Lakhs)': 'SPV వాటా (₹ లక్షలు)',
  'Government Grant (₹ Lakhs)': 'ప్రభుత్వ గ్రాంట్ (₹ లక్షలు)',
  'Bank Loan (₹ Lakhs)': 'బ్యాంకు రుణం (₹ లక్షలు)',
  'Other Sources (₹ Lakhs)': 'ఇతర వనరులు (₹ లక్షలు)',
  'Total Finance': 'మొత్తం నిధులు',
  'Raw Material Cost (₹ Lakhs)': 'ముడి పదార్థాల ఖర్చు (₹ లక్షలు)',
  'Power Cost (₹ Lakhs)': 'విద్యుత్ ఖర్చు (₹ లక్షలు)',
  'Wages (₹ Lakhs)': 'వేతనాలు (₹ లక్షలు)',
  'Maintenance (₹ Lakhs)': 'నిర్వహణ (₹ లక్షలు)',
  'Administrative Expenses (₹ Lakhs)': 'పరిపాలనా ఖర్చులు (₹ లక్షలు)',
  'Marketing Expenses (₹ Lakhs)': 'మార్కెటింగ్ ఖర్చులు (₹ లక్షలు)',
  'Annual Production Volume': 'వార్షిక ఉత్పత్తి పరిమాణం',
  'Annual Sales Realization (₹ Lakhs)': 'వార్షిక అమ్మకాలు (₹ లక్షలు)',
  'Basic Financial Indicators': 'ప్రాథమిక ఆర్థిక సూచికలు',
  'Break-even Point (₹ Lakhs)': 'బ్రేక్-ఈవెన్ పాయింట్ (₹ లక్షలు)',
  'IRR (%)': 'IRR (%)',
  'NPV (₹ Lakhs)': 'NPV (₹ లక్షలు)',
  'Sensitivity Analysis': 'సెన్సిటివిటీ విశ్లేషణ',
  'Start Date': 'ప్రారంభ తేదీ',
  'End Date': 'ముగింపు తేదీ',
  Milestones: 'మైలురాళ్లు',
  'Add Milestone': 'మైలురాయి జోడించండి',
  'Employment Generation': 'ఉపాధి సృష్టి',
  'Turnover Growth (%)': 'టర్నోవర్ వృద్ధి (%)',
  'Export Growth (%)': 'ఎగుమతి వృద్ధి (%)',
  'Income Enhancement (%)': 'ఆదాయ పెరుగుదల (%)',
  'Increase in Units': 'యూనిట్ల పెరుగుదల',
  'Sustainability Outcomes': 'సుస్థిర ఫలితాలు',
  'CFC Name': 'CFC పేరు',
  'Total Implementation Period': 'మొత్తం అమలు కాలం',
  'Building Estimates': 'భవన అంచనాలు',
  'Machinery Quotations': 'యంత్రాల కోటేషన్లు',
  'Member Registrations': 'సభ్య నమోదులు',
  'Building Plan': 'భవన ప్రణాళిక',
  'Quotations': 'కోటేషన్లు',
  'SPV Registration': 'SPV నమోదు',
  'Supporting Documents': 'సహాయక పత్రాలు',
  'Enter cluster name': 'క్లస్టర్ పేరు నమోదు చేయండి',
  'Enter district': 'జిల్లా నమోదు చేయండి',
  'Enter location': 'స్థలం నమోదు చేయండి',
  'Describe geographical spread': 'భౌగోళిక విస్తరణను వివరించండి',
  'Enter nature of business': 'వ్యాపార స్వభావం నమోదు చేయండి',
  'Enter major products': 'ప్రధాన ఉత్పత్తులు నమోదు చేయండి',
  'Enter sector type': 'రంగం రకం నమోదు చేయండి',
  'Describe the sector in detail': 'రంగాన్ని వివరంగా వర్ణించండి',
  'Describe national importance': 'జాతీయ ప్రాముఖ్యతను వివరించండి',
  'Describe state-level importance': 'రాష్ట్ర స్థాయి ప్రాముఖ్యతను వివరించండి',
  'Enter product name': 'ఉత్పత్తి పేరు నమోదు చేయండి',
  'Describe geography': 'భౌగోళికాన్ని వివరించండి',
  'Enter climate details': 'వాతావరణ వివరాలు నమోదు చేయండి',
  'Describe infrastructure': 'మౌలిక సదుపాయాలను వివరించండి',
  'Describe key economic activities': 'ప్రధాన ఆర్థిక కార్యకలాపాలను వివరించండి',
  'Describe raw material availability': 'ముడి పదార్థాల లభ్యతను వివరించండి',
  'Enter quantity': 'పరిమాణం నమోదు చేయండి',
  'Describe industrial infrastructure': 'పారిశ్రామిక మౌలిక సదుపాయాలను వివరించండి',
  'Enter road connectivity details': 'రోడ్డు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Enter rail connectivity details': 'రైలు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Enter port connectivity details': 'పోర్టు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Describe cluster evolution': 'క్లస్టర్ పరిణామాన్ని వివరించండి',
  'Describe present activities': 'ప్రస్తుత కార్యకలాపాలను వివరించండి',
  'Enter type of units': 'యూనిట్ల రకం నమోదు చేయండి',
  'Enter production capacity': 'ఉత్పత్తి సామర్థ్యం నమోదు చేయండి',
  'Enter technology level': 'సాంకేతిక స్థాయి నమోదు చేయండి',
  'Material name': 'పదార్థం పేరు',
  Source: 'మూలం',
  'Enter final product': 'తుది ఉత్పత్తి నమోదు చేయండి',
  'Stage name': 'దశ పేరు',
  'Enter SPV name': 'SPV పేరు నమోదు చేయండి',
  'Enter legal status': 'చట్టపరమైన స్థితి నమోదు చేయండి',
  'e.g., DIC, District': 'ఉదా: DIC, జిల్లా',
  'Activity name': 'కార్యకలాపం పేరు',
  'Separate multiple stakeholders with commas': 'బహుళ వాటాదారులను కామాలతో వేరు చేయండి',
  'Separate multiple products with commas': 'బహుళ ఉత్పత్తులను కామాలతో వేరు చేయండి',
  'Separate multiple buyers with commas': 'బహుళ కొనుగోలుదారులను కామాలతో వేరు చేయండి',
  'Separate multiple strengths with commas': 'బహుళ బలాలను కామాలతో వేరు చేయండి',
  'Separate multiple weaknesses with commas': 'బహుళ బలహీనతలను కామాలతో వేరు చేయండి',
  'Separate multiple opportunities with commas': 'బహుళ అవకాశాలను కామాలతో వేరు చేయండి',
  'Separate multiple threats with commas': 'బహుళ ముప్పులను కామాలతో వేరు చేయండి',
  'Separate multiple objectives with commas': 'బహుళ లక్ష్యాలను కామాలతో వేరు చేయండి',
  'Separate multiple benefits with commas': 'బహుళ ప్రయోజనాలను కామాలతో వేరు చేయండి',
  'Separate multiple roles with commas': 'బహుళ పాత్రలను కామాలతో వేరు చేయండి',
  'Separate multiple registrations with commas': 'బహుళ నమోదులను కామాలతో వేరు చేయండి',
  'Separate multiple outcomes with commas': 'బహుళ ఫలితాలను కామాలతో వేరు చేయండి',
  Designation: 'పదవి',
  'Share (%)': 'వాటా (%)',
  Registration: 'నమోదు',
  'Get AI Suggestions': 'AI సూచనలు పొందండి',
  'Get contextual recommendations based on your previous step data':
    'మునుపటి దశ డేటా ఆధారంగా సందర్భోచిత సిఫార్సులు పొందండి',
  'Generate Suggestions': 'సూచనలు రూపొందించండి',
  'Fill this step with AI': 'ఈ దశను AIతో నింపండి',
  'Fill this step': 'ఈ దశను నింపండి',
  'Filling…': 'నింపుతోంది…',
  'Getting suggestions…': 'సూచనలు పొందుతోంది…',
  'Suggests answers only for this step’s questions ({n}). Apply the ones you like.':
    'ఈ దశ ప్రశ్నలకు ({n}) మాత్రమే సమాధానాలు సూచిస్తుంది. మీకు నచ్చినవి వర్తింపజేయండి.',
  'Asking only this step’s catalog questions, one at a time.':
    'ఈ దశ కేటలాగ్ ప్రశ్నలు మాత్రమే, ఒక్కొక్కటిగా అడుగుతోంది.',
  'Suggesting {index}/{total}: {label}': 'సూచిస్తోంది {index}/{total}: {label}',
  'Asks only this step’s questions ({n}), one at a time.':
    'ఈ దశ ప్రశ్నలు ({n}) మాత్రమే, ఒక్కొక్కటిగా అడుగుతుంది.',
  'Filling {index}/{total}: {label}': 'నింపుతోంది {index}/{total}: {label}',
  'No questions to fill on this step.': 'ఈ దశలో నింపడానికి ప్రశ్నలు లేవు.',
  'Could not fill any fields for this step. Try again.':
    'ఈ దశలో ఏ ఫీల్డ్‌నూ నింపలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
  'Could not get suggestions for this step. Try again.':
    'ఈ దశకు సూచనలు పొందలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
  'Suggested {filled} of {total} questions on this step.':
    'ఈ దశలో {total}లో {filled} ప్రశ్నలకు సూచనలు వచ్చాయి.',
  'Suggested {n} questions on this step.': 'ఈ దశలో {n} ప్రశ్నలకు సూచనలు వచ్చాయి.',
  'Failed to get suggestions for this step': 'ఈ దశకు సూచనలు పొందడం విఫలమైంది',
  'Filled {filled} of {total} questions on this step.':
    'ఈ దశలో {total}లో {filled} ప్రశ్నలు నింపబడ్డాయి.',
  'Filled {n} questions on this step.': 'ఈ దశలో {n} ప్రశ్నలు నింపబడ్డాయి.',
  'Failed to fill this step with AI': 'ఈ దశను AIతో నింపడం విఫలమైంది',
  'Could not apply this suggestion. Try again.':
    'ఈ సూచనను వర్తింపజేయలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
  'Could not apply suggestions. Try again.':
    'సూచనలను వర్తింపజేయలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
  'Applied suggestion for {label}': '{label} కోసం సూచన వర్తింపజేయబడింది',
  'Applied {n} suggestions.': '{n} సూచనలు వర్తింపజేయబడ్డాయి.',
  'Failed to apply suggestion': 'సూచనను వర్తింపజేయడం విఫలమైంది',
  'Tell us what you want to add': 'మీరు ఏమి జోడించాలనుకుంటున్నారో చెప్పండి',
  'For: {label}': 'కోసం: {label}',
  'List the points or changes you want in the new answer. We will regenerate only this question.':
    'కొత్త సమాధానంలో కావాల్సిన పాయింట్లు లేదా మార్పులు రాయండి. ఈ ప్రశ్నను మాత్రమే మళ్లీ రూపొందిస్తాం.',
  'e.g. Mention local raw materials, add 2 more workers, keep it under 80 words':
    'ఉదా. స్థానిక ముడి పదార్థాలు చెప్పండి, మరో 2 కార్మికులు జోడించండి, 80 పదాలలోపు ఉంచండి',
  'Tell us what you want to add before regenerating.':
    'మళ్లీ రూపొందించే ముందు ఏమి జోడించాలో చెప్పండి.',
  'Could not regenerate this suggestion. Try again.':
    'ఈ సూచనను మళ్లీ రూపొందించలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
  'Suggestion regenerated.': 'సూచన మళ్లీ రూపొందించబడింది.',
  'Failed to regenerate suggestion': 'సూచనను మళ్లీ రూపొందించడం విఫలమైంది',
  'Regenerating…': 'మళ్లీ రూపొందిస్తోంది…',
  'Regenerate all suggestions for this step': 'ఈ దశ సూచనలన్నీ మళ్లీ రూపొందించండి',
  'Complete Step 1 first to get AI suggestions for this step.':
    'ఈ దశకు AI సూచనల కోసం ముందుగా దశ 1ని పూర్తి చేయండి.',
  'No suggestions available. Try generating again or fill in more fields.':
    'సూచనలు లేవు. మళ్లీ ప్రయత్నించండి లేదా మరిన్ని ఫీల్డ్‌లు నింపండి.',
  'Generating AI suggestions based on previous steps...': 'మునుపటి దశల ఆధారంగా AI సూచనలు రూపొందిస్తోంది...',
  'AI Suggestions': 'AI సూచనలు',
  Regenerate: 'మళ్లీ రూపొందించండి',
  'Apply All': 'అన్నీ వర్తింపజేయండి',
  'Applying...': 'వర్తింపజేస్తోంది...',
  Apply: 'వర్తింపజేయండి',
  Retry: 'మళ్లీ ప్రయత్నించండి',
  Confirm: 'నిర్ధారించండి',
  Cancel: 'రద్దు చేయండి',
  'Edit field': 'ఫీల్డ్‌ను సవరించండి',
  'Edit the full text, then Confirm to save or Cancel to discard.':
    'పూర్తి వచనాన్ని సవరించి, సేవ్ చేయడానికి నిర్ధారించండి లేదా విస్మరించడానికి రద్దు చేయండి.',
  'Improve this': 'దీన్ని మెరుగుపరచండి',
  'Improving…': 'మెరుగుపరుస్తోంది…',
  'Match me': 'నాకు సరిపోల్చు',
  'Matching…': 'సరిపోలుస్తోంది…',
  'What do you do': 'మీరు ఏం చేస్తారు',
  'Type what you do first, then Match me.':
    'ముందు మీరు ఏం చేస్తారో టైప్ చేసి, తర్వాత నాకు సరిపోల్చు నొక్కండి.',
  'Matched to: {skill}': 'సరిపోలింది: {skill}',
  'Could not match a skill. Try again with a clearer description.':
    'నైపుణ్యాన్ని సరిపోల్చలేకపోయాం. స్పష్టంగా వివరించి మళ్లీ ప్రయత్నించండి.',
  'Describe your work in a line, then Match me to map it to one skill.':
    'మీ పనిని ఒక లైన్‌లో రాసి, ఒక నైపుణ్యానికి సరిపోల్చడానికి నాకు సరిపోల్చు నొక్కండి.',
  'Type something first, then Improve this.':
    'ముందు ఏదైనా టైప్ చేసి, తర్వాత మెరుగుపరచండి.',
  'Could not improve this text. Try again.':
    'ఈ వచనాన్ని మెరుగుపరచలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
  'Improved — review, then Confirm to save.':
    'మెరుగుపరచబడింది — సమీక్షించి, సేవ్ చేయడానికి నిర్ధారించండి.',
  // Step-1 field tooltips
  'Enter the unit or project cover name used in official documents.':
    'అధికారిక పత్రాల్లో ఉపయోగించే యూనిట్ లేదా ప్రాజెక్ట్ కవర్ పేరు నమోదు చేయండి.',
  'Enter the official name of the industrial cluster. This should be the name used in official documents and registrations.':
    'పారిశ్రామిక క్లస్టర్ అధికారిక పేరు నమోదు చేయండి. అధికారిక పత్రాలు మరియు నమోదుల్లో ఉపయోగించే పేరు ఉండాలి.',
  'Select the Andhra Pradesh district where the unit is located.':
    'యూనిట్ ఉన్న ఆంధ్రప్రదేశ్ జిల్లాను ఎంచుకోండి.',
  'Specify the district where the cluster is located. This helps in regional analysis and government scheme eligibility.':
    'క్లస్టర్ ఉన్న జిల్లాను పేర్కొనండి. ప్రాంతీయ విశ్లేషణ మరియు ప్రభుత్వ పథక అర్హతకు ఇది సహాయపడుతుంది.',
  'Select the town where the unit is located (filtered by the district you chose).':
    'యూనిట్ ఉన్న పట్టణాన్ని ఎంచుకోండి (మీరు ఎంచుకున్న జిల్లా ఆధారంగా ఫిల్టర్ చేయబడుతుంది).',
  'Describe what you do in plain words, then use Match me to map it to one skill (e.g. “I make pots” → Pottery).':
    'మీరు ఏం చేస్తారో సాధారణ మాటల్లో రాసి, ఒక నైపుణ్యానికి సరిపోల్చడానికి నాకు సరిపోల్చు వాడండి (ఉదా. “నేను కుండలు చేస్తాను” → Pottery).',
  'List the main products you sell or make (e.g. pani puri, bhel puri).':
    'మీరు అమ్మే లేదా తయారు చేసే ప్రధాన ఉత్పత్తులు జాబితా చేయండి (ఉదా. పానీపూరి, భేల్ పూరి).',
  'List the main products manufactured or services provided by enterprises in the cluster.':
    'క్లస్టర్‌లోని సంస్థలు తయారు చేసే ప్రధాన ఉత్పత్తులు లేదా అందించే సేవలను జాబితా చేయండి.',
  // Common matched skills (display)
  'Street food / food stall': 'స్ట్రీట్ ఫుడ్ / ఫుడ్ స్టాల్',
  Pottery: 'కుమ్మరి / కుండల తయారీ',
  'Kirana / general store': 'కిరాణా / జనరల్ స్టోర్',
  'Tailoring / stitching': 'టైలరింగ్ / కుట్టు పని',
  Uploading: 'అప్‌లోడ్ అవుతోంది',
  Uploaded: 'అప్‌లోడ్ అయింది',
  'Raw Material': 'ముడి పదార్థం',
  Stage: 'దశ',
  Director: 'డైరెక్టర్',
  Shareholder: 'వాటాదారు',
  Unit: 'యూనిట్',
  'Unit name': 'యూనిట్ పేరు',
  'Describe sensitivity analysis': 'సెన్సిటివిటీ విశ్లేషణను వివరించండి',
  'Enter power requirements': 'విద్యుత్ అవసరాలు నమోదు చేయండి',
  'Enter water requirements': 'నీటి అవసరాలు నమోదు చేయండి',
  'Enter manpower requirements': 'మానవశక్తి అవసరాలు నమోదు చేయండి',
  'Unit / Project Name *': 'యూనిట్ / ప్రాజెక్ట్ పేరు *',
  'Enter unit or project name': 'యూనిట్ లేదా ప్రాజెక్ట్ పేరు నమోదు చేయండి',
  'Select district': 'జిల్లాను ఎంచుకోండి',
  'Select town': 'పట్టణం ఎంచుకోండి',
  'Select district first': 'ముందుగా జిల్లాను ఎంచుకోండి',
  Town: 'పట్టణం',
  'Village / town / industrial park': 'గ్రామం / పట్టణం / పారిశ్రామిక పార్క్',
  'Generate the rest of this DPR with AI': 'ఈ DPR మిగిలిన దశలను AIతో నింపండి',
  'Generate all steps with AI': 'అన్ని దశలను AIతో నింపండి',
  'PM Vishwakarma details': 'పీఎం విశ్వకర్మ వివరాలు',
  'Craft / trade': 'వృత్తి / కళ',
  'Select your craft': 'మీ వృత్తిని ఎంచుకోండి',
  'Current tools': 'ప్రస్తుత పనిముట్లు',
  'Tools you use today': 'మీరు ఇప్పుడు వాడే పనిముట్లు',
  'New tools needed (₹15,000 voucher)': 'కావాల్సిన కొత్త పనిముట్లు (₹15,000 వోచర్)',
  'Tools you want to buy with the voucher': 'వోచర్‌తో కొనాలనుకునే పనిముట్లు',
  'PM SVANidhi details': 'పీఎం స్వనిధి వివరాలు',
  'Vending proof': 'విక్రయ రుజువు',
  Select: 'ఎంచుకోండి',
  'Certificate of Vending (CoV)': 'వెండింగ్ సర్టిఫికేట్ (CoV)',
  'Letter of Recommendation (LoR)': 'సిఫార్సు పత్రం (LoR)',
  'UPI QR code': 'UPI QR కోడ్',
  'UPI ID or QR details': 'UPI ID లేదా QR వివరాలు',
  'FSSAI status': 'FSSAI స్థితి',
  'Already have FSSAI': 'FSSAI ఇప్పటికే ఉంది',
  'Will obtain / draft FSSAI': 'FSSAI తీసుకుంటాను / డ్రాఫ్ట్',
  'APIIC industrial park': 'APIIC పారిశ్రామిక పార్క్',
  'Is the unit inside an APIIC park?': 'యూనిట్ APIIC పార్క్‌లో ఉందా?',
  'Yes — land rebate may apply': 'అవును — భూమి రాయితీ వర్తించవచ్చు',
  No: 'కాదు',
  'How your unit evolved': 'మీ యూనిట్ ఎలా ఎదిగింది',
  'Describe how the unit evolved': 'యూనిట్ ఎలా ఎదిగిందో వివరించండి',
  'Type of unit': 'యూనిట్ రకం',
  'Unit / shed / workplace name': 'యూనిట్ / షెడ్ / కార్యస్థలం పేరు',
  'Mudra Nayak working capital': 'ముద్ర నాయక్ వర్కింగ్ క్యాపిటల్',
  'DSCR (profit + depreciation vs EMI)': 'DSCR (లాభం + తరుగుదల vs EMI)',
  '8th-pass / education certificate': '8వ తరగతి / విద్యా సర్టిఫికేట్',
  'Know which scheme you want? Vanilla bank term loan': 'పథకం తెలుసా? సాధారణ బ్యాంకు టర్మ్ లోన్',
  'Vanilla bank term loan': 'సాధారణ బ్యాంకు టర్మ్ లోన్',
  'PM Vishwakarma': 'పీఎం విశ్వకర్మ',
  'PM SVANidhi': 'పీఎం స్వనిధి',
  'Step list drops 15, 16, 17 (15 steps instead of 18).': 'దశల జాబితా 15, 16, 17ని తీసివేస్తుంది (18కి బదులు 15).',
  'Step 1 adds craft + current/new tools (₹15,000 voucher).': 'దశ 1లో వృత్తి + ప్రస్తుత/కొత్త పనిముట్లు (₹15,000 వోచర్) జోడవుతాయి.',
  'Step 18 uploads: Aadhaar, passbook, ration card.': 'దశ 18 అప్‌లోడ్లు: ఆధార్, పాస్‌బుక్, రేషన్ కార్డు.',
  'Step list drops 15, 16, 17.': 'దశల జాబితా 15, 16, 17ని తీసివేస్తుంది.',
  'Step 1 adds CoV vs LoR and UPI QR.': 'దశ 1లో CoV vs LoR మరియు UPI QR జోడవుతాయి.',
  'Step 18 upload: CoV or Letter of Recommendation.': 'దశ 18 అప్‌లోడ్: CoV లేదా సిఫార్సు పత్రం.',
  'Steps 1–17 stay the same length.': 'దశలు 1–17 పొడవు మారదు.',
  'Step 1 adds FSSAI yes/planned.': 'దశ 1లో FSSAI అవును/ప్రణాళిక జోడవుతుంది.',
  'Step 18 uploads: quotations, premises lease, draft FSSAI.': 'దశ 18 అప్‌లోడ్లు: కోటేషన్లు, ప్రాంగణం లీజు, డ్రాఫ్ట్ FSSAI.',
  'All 18 steps. No scheme extras on step 1.': 'అన్ని 18 దశలు. దశ 1లో పథక అదనపు ఫీల్డ్‌లు లేవు.',
  'Step 18: Aadhaar/PAN, Udyam, passbook, machinery quotations.': 'దశ 18: ఆధార్/PAN, ఉద్యమ్, పాస్‌బుక్, యంత్రాల కోటేషన్లు.',
  'No extra fields on steps 1–17 for this scheme in v1.': 'ఈ పథకానికి v1లో దశలు 1–17పై అదనపు ఫీల్డ్‌లు లేవు.',
  'Step 18 uses the default individual upload list (Aadhaar/PAN, Udyam, passbook, quotations).': 'దశ 18 డిఫాల్ట్ వ్యక్తిగత అప్‌లోడ్ జాబితా వాడుతుంది (ఆధార్/PAN, ఉద్యమ్, పాస్‌బుక్, కోటేషన్లు).',
  'Core questions on steps 1–17 do not change.': 'దశలు 1–17లోని ప్రధాన ప్రశ్నలు మారవు.',
  'Step 18 uploads: machinery quotes, building estimate (caste cert if SC/ST/BC from VentureMatch).': 'దశ 18 అప్‌లోడ్లు: యంత్రాల కోట్లు, భవన అంచనా (VentureMatch నుండి SC/ST/BC అయితే కుల సర్టిఫికేట్).',
  '8th-pass upload appears on step 18 if project cost is above the PMEGP education gate.': 'ప్రాజెక్ట్ ఖర్చు PMEGP విద్యా పరిమితి మించితే దశ 18లో 8వ తరగతి అప్‌లోడ్ కనిపిస్తుంది.',
  'Step 12 hides land/building tables only if VentureMatch budget is under ₹5L (Shishu/Kishore).': 'VentureMatch బడ్జెట్ ₹5 లక్షల లోపు (శిశు/కిషోర్) అయితేనే దశ 12 భూమి/భవన పట్టికలను దాచుతుంది.',
  'Step 15 shows Nayak WC (20% of turnover, 5% margin) for that same budget band.': 'దశ 15 అదే బడ్జెట్ బ్యాండ్‌కు నాయక్ WC (టర్నోవర్‌లో 20%, 5% మార్జిన్) చూపిస్తుంది.',
  'Step 18: shop proof, bank statements, quotes (+ Mudra closure if Tarun Plus).': 'దశ 18: దుకాణ రుజువు, బ్యాంకు స్టేట్‌మెంట్లు, కోట్లు (+ తరుణ్ ప్లస్ అయితే ముద్ర క్లోజర్).',
  'Step 1 asks if the unit is in an APIIC park (land-rebate hint).': 'దశ 1 యూనిట్ APIIC పార్క్‌లో ఉందో అడుగుతుంది (భూమి రాయితీ సూచన).',
  'Step 12 keeps land / building / P&M (FCI).': 'దశ 12 భూమి / భవనం / P&M (FCI) ఉంచుతుంది.',
  'Step 18: land/shed, CFE/CFO, CA FCI statement.': 'దశ 18: భూమి/షెడ్, CFE/CFO, CA FCI స్టేట్‌మెంట్.',
  'Uses the unit name, district, and location to fill every visible step except document uploads. You can edit anything afterwards.':
    'యూనిట్ పేరు, జిల్లా, స్థలం ఉపయోగించి డాక్యుమెంట్ అప్‌లోడ్లు తప్ప అన్ని కనిపించే దశలను నింపుతుంది. తర్వాత ఏదైనా సవరించవచ్చు.',
  Aadhaar: 'ఆధార్',
  'Savings Bank Passbook': 'సేవింగ్స్ బ్యాంకు పాస్‌బుక్',
  'Ration Card (family verification)': 'రేషన్ కార్డు (కుటుంబ ధృవీకరణ)',
  'Certificate of Vending (CoV) or Letter of Recommendation': 'వెండింగ్ సర్టిఫికేట్ (CoV) లేదా సిఫార్సు పత్రం',
  'Aadhaar / PAN': 'ఆధార్ / PAN',
  'Udyam Certificate': 'ఉద్యమ్ సర్టిఫికేట్',
  'Bank Passbook': 'బ్యాంకు పాస్‌బుక్',
  'Machinery / Equipment Quotations': 'యంత్రాల / పరికరాల కోటేషన్లు',
  Question: 'ప్రశ్న',
  Answer: 'సమాధానం',
  Section: 'విభాగం',
  Document: 'పత్రం',
  Status: 'స్థితి',
  Pending: 'పెండింగ్',
  On: 'పై',
  'Table of Contents': 'విషయ సూచిక',
  'No answers for this section yet.': 'ఈ విభాగానికి ఇంకా సమాధానాలు లేవు.',
  'Not filled': 'నింపలేదు',
  'Not filled yet — complete this in the form.': 'ఇంకా నింపలేదు — ఫారమ్‌లో దీన్ని పూర్తి చేయండి.',
  'Describe civil works': 'సివిల్ పనులను వివరించండి',
  'Describe competitor analysis': 'పోటీ విశ్లేషణను వివరించండి',
  'Describe demand-supply gap': 'డిమాండ్-సప్లై అంతరాన్ని వివరించండి',
  'Describe existing demand': 'ప్రస్తుత డిమాండ్‌ను వివరించండి',
  'Describe export potential': 'ఎగుమతి సామర్థ్యాన్ని వివరించండి',
  'Describe financial gaps': 'ఆర్థిక అంతరాలను వివరించండి',
  'Describe infrastructure gaps': 'మౌలిక సదుపాయాల అంతరాలను వివరించండి',
  'Describe manufacturing process': 'తయారీ ప్రక్రియను వివరించండి',
  'Describe marketing gaps': 'మార్కెటింగ్ అంతరాలను వివరించండి',
  'Describe plant & machinery': 'ప్లాంట్ మరియు యంత్రాలను వివరించండి',
  'Describe price trends': 'ధరల ధోరణులను వివరించండి',
  'Describe skill gaps': 'నైపుణ్య అంతరాలను వివరించండి',
  'Describe target market': 'లక్ష్య మార్కెట్‌ను వివరించండి',
  'Describe technology gaps': 'సాంకేతిక అంతరాలను వివరించండి',
  'Describe the intervention': 'జోక్యాన్ని వివరించండి',
  'End date': 'ముగింపు తేదీ',
  'Enter CFC name': 'CFC పేరు నమోదు చేయండి',
  'Enter applicant or firm name': 'దరఖాస్తుదారు లేదా సంస్థ పేరు నమోదు చేయండి',
  'Enter capacity': 'సామర్థ్యం నమోదు చేయండి',
  'Enter expected benefits separated by commas (e.g., Benefit 1, Benefit 2, Benefit 3)':
    'ఊహించిన ప్రయోజనాలను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter intermediate products separated by commas (e.g., Semi-finished Product 1, Semi-finished Product 2)':
    'మధ్యంతర ఉత్పత్తులను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter land details': 'భూమి వివరాలు నమోదు చేయండి',
  'Enter major buyers separated by commas (e.g., Buyer 1, Buyer 2, Buyer 3)':
    'ప్రధాన కొనుగోలుదారులను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter objective': 'లక్ష్యం నమోదు చేయండి',
  'Enter objectives separated by commas (e.g., Objective 1, Objective 2, Objective 3)':
    'లక్ష్యాలను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter opportunities separated by commas (e.g., Growing market demand, Government support, Export potential)':
    'అవకాశాలను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter roles and responsibilities separated by commas (e.g., Role 1, Role 2, Role 3)':
    'పాత్రలు మరియు బాధ్యతలను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter stakeholders separated by commas (e.g., Stakeholder 1, Stakeholder 2, Stakeholder 3)':
    'వాటాదారులను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter statutory registrations separated by commas (e.g., Registration 1, Registration 2, Registration 3)':
    'చట్టబద్ధ నమోదులను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter strengths separated by commas (e.g., Strong market presence, Skilled workforce, Good infrastructure)':
    'బలాలను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter sustainability outcomes separated by commas (e.g., Outcome 1, Outcome 2, Outcome 3)':
    'సుస్థిరత ఫలితాలను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter threats separated by commas (e.g., Market competition, Price fluctuations, Regulatory changes)':
    'ముప్పులను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter weaknesses separated by commas (e.g., Limited technology, Lack of skilled workers, Poor infrastructure)':
    'బలహీనతలను కామాతో వేరు చేసి నమోదు చేయండి',
  'Enter workplace or shed name': 'పని స్థలం లేదా షెడ్ పేరు నమోదు చేయండి',
  Milestone: 'మైలురాయి',
  'Min own': 'కనీస స్వంతం',
  'Percentage (%)': 'శాతం (%)',
  'Provide justification for intervention': 'జోక్యానికి సమర్థన ఇవ్వండి',
  'Registration number': 'నమోదు సంఖ్య',
  'Short impact note (optional)': 'చిన్న ప్రభావ గమనిక (ఐచ్ఛికం)',
  'Stakeholder name': 'వాటాదారు పేరు',
  'Start date': 'ప్రారంభ తేదీ',
  'Time required': 'అవసరమైన సమయం',
  YYYY: 'YYYY',
  'e.g. 200 units/day': 'ఉదా. రోజుకు 200 యూనిట్లు',
  'e.g. 50 kg/hour or 1000 units/month': 'ఉదా. గంటకు 50 కిలోలు లేదా నెలకు 1000 యూనిట్లు',
  'e.g. 60': 'ఉదా. 60',
  'e.g. 8 kW': 'ఉదా. 8 kW',
  'e.g. Apr 2026': 'ఉదా. ఏప్రి 2026',
  'e.g., 18 months': 'ఉదా. 18 నెలలు',
  'Raw Material {n}': 'ముడి పదార్థం {n}',
  'Stage {n}': 'దశ {n}',
  'Project cost': 'ప్రాజెక్ట్ ఖర్చు',
  'Equity + loan + other': 'ఈక్విటీ + రుణం + ఇతర',
  'Projected annual turnover (₹ Lakhs)': 'అంచనా వార్షిక టర్నోవర్ (₹ లక్షలు)',
  'WC limit (20%)': 'WC పరిమితి (20%)',
  'Promoter margin (5% of WC)': 'ప్రమోటర్ మార్జిన్ (WCలో 5%)',
  Year: 'సంవత్సరం',
  Sales: 'అమ్మకాలు',
  RM: 'ముడి పదార్థం',
  Wages: 'వేతనాలు',
  Power: 'విద్యుత్',
  'Net profit': 'నికర లాభం',
  'Spec: docs/schemes/AP_EDP/apEdp.md — greenfield FCI capital subsidy; mutually exclusive with tech-upgrade':
    'కొత్త యూనిట్ FCI మూలధన సబ్సిడీ; టెక్-అప్‌గ్రేడ్‌తో కలిపి పొందలేరు',
  'Spec: docs/schemes/AP_FPP/apFpp.md — do not double-claim with AP_EDP':
    'AP EDPతో రెండుసార్లు క్లెయిమ్ చేయవద్దు',
  'Spec: docs/schemes/AP_PARKS/apParks.md': 'AP పార్కుల యూనిట్ ప్యాక్',
  'Spec: docs/schemes/AP_TECH_UPGRADE/apTechUpgrade.md — brownfield FCI; mutually exclusive with new-unit EDP capital subsidy':
    'ఉన్న యూనిట్ FCI అప్‌గ్రేడ్; కొత్త యూనిట్ EDP మూలధన సబ్సిడీతో కలిపి పొందలేరు',
  'Spec: docs/schemes/ASPIRE/aspire.md': 'ASPIRE యూనిట్ ప్యాక్',
  'Spec: docs/schemes/CGTMSE/cgtmse.md': 'CGTMSE హామీ ప్యాక్',
  'Spec: docs/schemes/CVY/cvy.md': 'కొబ్బరి వికాస్ యోజన ప్యాక్',
  'Spec: docs/schemes/ECLGS/eclgs.md — additional WC up to 20% of peak Q4 outstanding':
    'అదనపు వర్కింగ్ క్యాపిటల్ — గరిష్ట Q4 బకాయిలో 20% వరకు',
  'Spec: docs/schemes/EPM_NIRYAT/epmNiryat.md — 2.75% interest subvention':
    'ఎగుమతి వడ్డీ సబ్సిడీ 2.75%',
  'Spec: docs/schemes/LEAN/lean.md': 'LEAN ప్యాక్',
  'Spec: docs/schemes/MSE_GIFT/mseGift.md': 'MSE-GIFT ప్యాక్',
  'Spec: docs/schemes/MSE_SPICE/mseSpice.md — 25% P&M cap ₹12.5 L':
    'P&Mపై 25%, పరిమితి ₹12.5 లక్షలు',
  'Spec: docs/schemes/MSME_IPR/msmeIpr.md': 'MSME IPR ప్యాక్',
  'Spec: docs/schemes/MUDRA/mudra.md — Shishu / Kishore / Tarun / Tarun Plus':
    'ముద్ర — శిశు / కిషోర్ / తరుణ్ / తరుణ్ ప్లస్',
  'Spec: docs/schemes/NHDP/nhdp.md': 'NHDP ప్యాక్',
  'Spec: docs/schemes/OBMMS/obmms.md': 'OBMMS ప్యాక్',
  'Spec: docs/schemes/PMEGP_2ND/pmegp2nd.md — brownfield only; uniform 15% MM (20% NER/Hill); own 10%':
    'ఉన్న యూనిట్ మాత్రమే; ఏకరూప మార్జిన్ మనీ 15% (NER/హిల్ 20%); స్వంతం 10%',
  'Spec: docs/schemes/PMFME/pmfme.md — NIFTEM model DPRs; 35% grant capped ₹10 L; own ≥10%':
    'NIFTEM మోడల్ DPR; 35% గ్రాంట్, పరిమితి ₹10 లక్షలు; స్వంతం ≥10%',
  'Spec: docs/schemes/PMPDS/pmpds.md': 'PMPDS ప్యాక్',
  'Spec: docs/schemes/PMS/pms.md': 'సేకరణ మరియు మార్కెటింగ్ పథకం',
  'Spec: docs/schemes/PTUAS/ptuas.md': 'PTUAS ప్యాక్',
  'Spec: docs/schemes/RAMP_TEAM/rampTeam.md': 'RAMP TEAM ప్యాక్',
  'Spec: docs/schemes/SCLCSS/sclcss.md — 25% on new P&M, cap ₹25 L; SC/ST ≥51%; not general CLCSS':
    'కొత్త P&Mపై 25%, పరిమితి ₹25 లక్షలు; SC/ST ≥51%',
  'Spec: docs/schemes/SCST_HUB/scstHub.md': 'SC/ST హబ్ ప్యాక్',
  'Spec: docs/schemes/STANDUP/standup.md — woman / SC / ST, greenfield, ≥10% own, ₹10 L–₹1 Cr':
    'మహిళ / SC / ST, కొత్త యూనిట్, స్వంతం ≥10%, ₹10 లక్షలు–₹1 కోటి',
  'Spec: docs/schemes/SVANIDHI/svanidhi.md — WC tranches ₹15k / ₹25k / ₹50k; 7% interest subsidy; UPI mandatory':
    'వర్కింగ్ క్యాపిటల్ విడతలు ₹15 వేలు / ₹25 వేలు / ₹50 వేలు; 7% వడ్డీ సబ్సిడీ; UPI తప్పనిసరి',
  'Spec: docs/schemes/VISHWAKARMA/vishwakarma.md — 18 trades; toolkit ₹15,000; loan ₹1 L then ₹2 L at 5%':
    '18 వృత్తులు; టూల్‌కిట్ ₹15,000; రుణం ₹1 లక్ష తర్వాత ₹2 లక్షలు, 5%',
  'Spec: docs/schemes/ZED/zed.md': 'ZED ప్యాక్',
};

export function useClusterFormText() {
  const { i18n } = useTranslation();
  const lang = (i18n.resolvedLanguage || i18n.language || 'en').toLowerCase();
  const isTe = lang.startsWith('te');
  return useCallback(
    (en: string) => {
      if (!en) return en;
      if (!isTe) return en;
      return TE[en] || en;
    },
    [isTe]
  );
}
