import { useTranslation } from 'react-i18next';

/** English UI string → Telugu. Missing keys fall back to English. */
const TE: Record<string, string> = {
  'Cluster Name *': 'క్లస్టర్ పేరు *',
  'District *': 'జిల్లా *',
  'Location *': 'స్థలం *',
  'Geographical Spread': 'భౌగోళిక విస్తరణ',
  'Nature of Business': 'వ్యాపార స్వభావం',
  'Major Products': 'ప్రధాన ఉత్పత్తులు',
  'Enterprise Count': 'ఎంటర్‌ప్రైజ్‌ల సంఖ్య',
  Micro: 'మైక్రో',
  Small: 'చిన్న',
  Medium: 'మధ్యస్థ',
  'Age of Enterprises': 'ఎంటర్‌ప్రైజ్‌ల వయసు',
  '< 5 years': '5 సంవత్సరాల లోపు',
  '5-10 years': '5-10 సంవత్సరాలు',
  '> 10 years': '10 సంవత్సరాలు పైన',
  'Employment per Unit': 'యూనిట్‌కు ఉపాధి',
  '< 5 employees': '5 మంది లోపు',
  '5-10 employees': '5-10 మంది',
  '> 10 employees': '10 మంది పైన',
  'Investment per Unit (₹ Lakhs)': 'యూనిట్‌కు పెట్టుబడి (₹ లక్షలు)',
  'Turnover per Unit (₹ Lakhs)': 'యూనిట్‌కు టర్నోవర్ (₹ లక్షలు)',
  'Market Served (%)': 'సేవ చేసే మార్కెట్ (%)',
  Domestic: 'దేశీయ',
  Export: 'ఎగుమతి',
  'Sector / Industry Type': 'రంగం / పరిశ్రమ రకం',
  'Sector Description': 'రంగం వివరణ',
  'National Importance': 'జాతీయ ప్రాముఖ్యత',
  'State-level Importance': 'రాష్ట్ర స్థాయి ప్రాముఖ్యత',
  'Key Products': 'ప్రధాన ఉత్పత్తులు',
  'Add Product': 'ఉత్పత్తి జోడించండి',
  Geography: 'భౌగోళికం',
  Climate: 'వాతావరణం',
  Infrastructure: 'మౌలిక సదుపాయాలు',
  'Key Economic Activities': 'ప్రధాన ఆర్థిక కార్యకలాపాలు',
  'Raw Material Availability': 'ముడి పదార్థాల లభ్యత',
  'Raw Material Quantity': 'ముడి పదార్థాల పరిమాణం',
  'Industrial Infrastructure': 'పారిశ్రామిక మౌలిక సదుపాయాలు',
  Connectivity: 'కనెక్టివిటీ',
  Road: 'రోడ్డు',
  Rail: 'రైలు',
  Port: 'పోర్టు',
  'Year of Establishment': 'స్థాపన సంవత్సరం',
  'Cluster Evolution': 'క్లస్టర్ పరిణామం',
  'Present Activities': 'ప్రస్తుత కార్యకలాపాలు',
  'Type of Units': 'యూనిట్ల రకం',
  'Production Capacity': 'ఉత్పత్తి సామర్థ్యం',
  'Technology Level': 'సాంకేతిక స్థాయి',
  Stakeholders: 'వాటాదారులు',
  'Raw Materials': 'ముడి పదార్థాలు',
  'Add Raw Material': 'ముడి పదార్థం జోడించండి',
  'Intermediate Products': 'మధ్యంతర ఉత్పత్తులు',
  'Final Products': 'తుది ఉత్పత్తులు',
  'Add Final Product': 'తుది ఉత్పత్తి జోడించండి',
  'Value Addition Stages': 'విలువ జోడింపు దశలు',
  'Add Value Addition Stage': 'విలువ జోడింపు దశను జోడించండి',
  'Major Buyers': 'ప్రధాన కొనుగోలుదారులు',
  'Existing Demand': 'ప్రస్తుత డిమాండ్',
  'Demand-Supply Gap': 'డిమాండ్-సప్లై అంతరం',
  'Target Market': 'లక్ష్య మార్కెట్',
  'Competitor Analysis': 'పోటీ విశ్లేషణ',
  'Price Trends': 'ధరల ధోరణులు',
  'Export Potential': 'ఎగుమతి సామర్థ్యం',
  'Technology Gaps': 'సాంకేతిక అంతరాలు',
  'Infrastructure Gaps': 'మౌలిక సదుపాయాల అంతరాలు',
  'Skill Gaps': 'నైపుణ్య అంతరాలు',
  'Marketing Gaps': 'మార్కెటింగ్ అంతరాలు',
  'Financial Gaps': 'ఆర్థిక అంతరాలు',
  'Justification for Intervention': 'జోక్యానికి సమర్థన',
  Strengths: 'బలాలు',
  Weaknesses: 'బలహీనతలు',
  Opportunities: 'అవకాశాలు',
  Threats: 'ముప్పులు',
  'Intervention Type': 'జోక్యం రకం',
  'Select type': 'రకం ఎంచుకోండి',
  Hard: 'హార్డ్',
  Soft: 'సాఫ్ట్',
  Both: 'రెండూ',
  Description: 'వివరణ',
  Objectives: 'లక్ష్యాలు',
  'Add Objective': 'లక్ష్యం జోడించండి',
  'Expected Benefits': 'ఆశించిన ప్రయోజనాలు',
  Name: 'పేరు',
  Location: 'స్థలం',
  'Land Details': 'భూమి వివరాలు',
  'Civil Works': 'సివిల్ పనులు',
  'Manufacturing Process': 'తయారీ ప్రక్రియ',
  'Plant & Machinery': 'ప్లాంట్ మరియు యంత్రాలు',
  Capacity: 'సామర్థ్యం',
  'Power Requirements': 'విద్యుత్ అవసరాలు',
  'Water Requirements': 'నీటి అవసరాలు',
  'Manpower Requirements': 'మానవశక్తి అవసరాలు',
  'SPV Name': 'SPV పేరు',
  'Legal Status': 'చట్టపరమైన స్థితి',
  'Year of Incorporation': 'నమోదు సంవత్సరం',
  'Submitted To': 'సమర్పించిన సంస్థ',
  'Roles & Responsibilities': 'పాత్రలు మరియు బాధ్యతలు',
  'Board of Directors': 'డైరెక్టర్ల బోర్డు',
  'Add Director': 'డైరెక్టర్ జోడించండి',
  'Shareholding Pattern': 'వాటా నమూనా',
  'Add Shareholder': 'వాటాదారుని జోడించండి',
  'Member Units': 'సభ్య యూనిట్లు',
  'Add Member Unit': 'సభ్య యూనిట్ జోడించండి',
  'Statutory Registrations': 'చట్టబద్ధమైన నమోదులు',
  'Land (₹ Lakhs)': 'భూమి (₹ లక్షలు)',
  'Building (₹ Lakhs)': 'భవనం (₹ లక్షలు)',
  'Machinery (₹ Lakhs)': 'యంత్రాలు (₹ లక్షలు)',
  'Utilities & Infrastructure (₹ Lakhs)': 'యుటిలిటీలు & మౌలిక సదుపాయాలు (₹ లక్షలు)',
  'Preliminary & Pre-operative (₹ Lakhs)': 'ప్రాథమిక & ప్రీ-ఆపరేటివ్ (₹ లక్షలు)',
  'Working Capital Margin (₹ Lakhs)': 'వర్కింగ్ క్యాపిటల్ మార్జిన్ (₹ లక్షలు)',
  'Total Project Cost': 'మొత్తం ప్రాజెక్ట్ ఖర్చు',
  Lakhs: 'లక్షలు',
  'SPV Contribution (₹ Lakhs)': 'SPV వాటా (₹ లక్షలు)',
  'Government Grant (₹ Lakhs)': 'ప్రభుత్వ గ్రాంట్ (₹ లక్షలు)',
  'Bank Loan (₹ Lakhs)': 'బ్యాంకు రుణం (₹ లక్షలు)',
  'Other Sources (₹ Lakhs)': 'ఇతర వనరులు (₹ లక్షలు)',
  'Total Finance': 'మొత్తం నిధులు',
  'Raw Material Cost (₹ Lakhs)': 'ముడి పదార్థాల ఖర్చు (₹ లక్షలు)',
  'Power Cost (₹ Lakhs)': 'విద్యుత్ ఖర్చు (₹ లక్షలు)',
  'Wages (₹ Lakhs)': 'వేతనాలు (₹ లక్షలు)',
  'Maintenance (₹ Lakhs)': 'నిర్వహణ (₹ లక్షలు)',
  'Administrative Expenses (₹ Lakhs)': 'పరిపాలనా ఖర్చులు (₹ లక్షలు)',
  'Marketing Expenses (₹ Lakhs)': 'మార్కెటింగ్ ఖర్చులు (₹ లక్షలు)',
  'Annual Production Volume': 'వార్షిక ఉత్పత్తి పరిమాణం',
  'Annual Sales Realization (₹ Lakhs)': 'వార్షిక అమ్మకాలు (₹ లక్షలు)',
  'Basic Financial Indicators': 'ప్రాథమిక ఆర్థిక సూచికలు',
  'Break-even Point (₹ Lakhs)': 'బ్రేక్-ఈవెన్ పాయింట్ (₹ లక్షలు)',
  'IRR (%)': 'IRR (%)',
  'NPV (₹ Lakhs)': 'NPV (₹ లక్షలు)',
  'Sensitivity Analysis': 'సెన్సిటివిటీ విశ్లేషణ',
  'Start Date': 'ప్రారంభ తేదీ',
  'End Date': 'ముగింపు తేదీ',
  Milestones: 'మైలురాళ్లు',
  'Add Milestone': 'మైలురాయి జోడించండి',
  'Employment Generation': 'ఉపాధి సృష్టి',
  'Turnover Growth (%)': 'టర్నోవర్ వృద్ధి (%)',
  'Export Growth (%)': 'ఎగుమతి వృద్ధి (%)',
  'Income Enhancement (%)': 'ఆదాయ పెరుగుదల (%)',
  'Increase in Units': 'యూనిట్ల పెరుగుదల',
  'Sustainability Outcomes': 'సుస్థిర ఫలితాలు',
  'CFC Name': 'CFC పేరు',
  'Total Implementation Period': 'మొత్తం అమలు కాలం',
  'Building Estimates': 'భవన అంచనాలు',
  'Machinery Quotations': 'యంత్రాల కోటేషన్లు',
  'Member Registrations': 'సభ్య నమోదులు',
  'Building Plan': 'భవన ప్రణాళిక',
  'Quotations': 'కోటేషన్లు',
  'SPV Registration': 'SPV నమోదు',
  'Supporting Documents': 'సహాయక పత్రాలు',
  'Enter cluster name': 'క్లస్టర్ పేరు నమోదు చేయండి',
  'Enter district': 'జిల్లా నమోదు చేయండి',
  'Enter location': 'స్థలం నమోదు చేయండి',
  'Describe geographical spread': 'భౌగోళిక విస్తరణను వివరించండి',
  'Enter nature of business': 'వ్యాపార స్వభావం నమోదు చేయండి',
  'Enter major products': 'ప్రధాన ఉత్పత్తులు నమోదు చేయండి',
  'Enter sector type': 'రంగం రకం నమోదు చేయండి',
  'Describe the sector in detail': 'రంగాన్ని వివరంగా వర్ణించండి',
  'Describe national importance': 'జాతీయ ప్రాముఖ్యతను వివరించండి',
  'Describe state-level importance': 'రాష్ట్ర స్థాయి ప్రాముఖ్యతను వివరించండి',
  'Enter product name': 'ఉత్పత్తి పేరు నమోదు చేయండి',
  'Describe geography': 'భౌగోళికాన్ని వివరించండి',
  'Enter climate details': 'వాతావరణ వివరాలు నమోదు చేయండి',
  'Describe infrastructure': 'మౌలిక సదుపాయాలను వివరించండి',
  'Describe key economic activities': 'ప్రధాన ఆర్థిక కార్యకలాపాలను వివరించండి',
  'Describe raw material availability': 'ముడి పదార్థాల లభ్యతను వివరించండి',
  'Enter quantity': 'పరిమాణం నమోదు చేయండి',
  'Describe industrial infrastructure': 'పారిశ్రామిక మౌలిక సదుపాయాలను వివరించండి',
  'Enter road connectivity details': 'రోడ్డు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Enter rail connectivity details': 'రైలు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Enter port connectivity details': 'పోర్టు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Describe cluster evolution': 'క్లస్టర్ పరిణామాన్ని వివరించండి',
  'Describe present activities': 'ప్రస్తుత కార్యకలాపాలను వివరించండి',
  'Enter type of units': 'యూనిట్ల రకం నమోదు చేయండి',
  'Enter production capacity': 'ఉత్పత్తి సామర్థ్యం నమోదు చేయండి',
  'Enter technology level': 'సాంకేతిక స్థాయి నమోదు చేయండి',
  'Material name': 'పదార్థం పేరు',
  Source: 'మూలం',
  'Enter final product': 'తుది ఉత్పత్తి నమోదు చేయండి',
  'Stage name': 'దశ పేరు',
  'Enter SPV name': 'SPV పేరు నమోదు చేయండి',
  'Enter legal status': 'చట్టపరమైన స్థితి నమోదు చేయండి',
  'e.g., DIC, District': 'ఉదా: DIC, జిల్లా',
  'Activity name': 'కార్యకలాపం పేరు',
  'Separate multiple stakeholders with commas': 'బహుళ వాటాదారులను కామాలతో వేరు చేయండి',
  'Separate multiple products with commas': 'బహుళ ఉత్పత్తులను కామాలతో వేరు చేయండి',
  'Separate multiple buyers with commas': 'బహుళ కొనుగోలుదారులను కామాలతో వేరు చేయండి',
  'Separate multiple strengths with commas': 'బహుళ బలాలను కామాలతో వేరు చేయండి',
  'Separate multiple weaknesses with commas': 'బహుళ బలహీనతలను కామాలతో వేరు చేయండి',
  'Separate multiple opportunities with commas': 'బహుళ అవకాశాలను కామాలతో వేరు చేయండి',
  'Separate multiple threats with commas': 'బహుళ ముప్పులను కామాలతో వేరు చేయండి',
  'Separate multiple objectives with commas': 'బహుళ లక్ష్యాలను కామాలతో వేరు చేయండి',
  'Separate multiple benefits with commas': 'బహుళ ప్రయోజనాలను కామాలతో వేరు చేయండి',
  'Separate multiple roles with commas': 'బహుళ పాత్రలను కామాలతో వేరు చేయండి',
  'Separate multiple registrations with commas': 'బహుళ నమోదులను కామాలతో వేరు చేయండి',
  'Separate multiple outcomes with commas': 'బహుళ ఫలితాలను కామాలతో వేరు చేయండి',
  Designation: 'పదవి',
  'Share (%)': 'వాటా (%)',
  Registration: 'నమోదు',
  'Get AI Suggestions': 'AI సూచనలు పొందండి',
  'Get contextual recommendations based on your previous step data':
    'మునుపటి దశ డేటా ఆధారంగా సందర్భోచిత సిఫార్సులు పొందండి',
  'Generate Suggestions': 'సూచనలు రూపొందించండి',
  'Complete Step 1 first to get AI suggestions for this step.':
    'ఈ దశకు AI సూచనల కోసం ముందుగా దశ 1ని పూర్తి చేయండి.',
  'No suggestions available. Try generating again or fill in more fields.':
    'సూచనలు లేవు. మళ్లీ ప్రయత్నించండి లేదా మరిన్ని ఫీల్డ్‌లు నింపండి.',
  'Generating AI suggestions based on previous steps...': 'మునుపటి దశల ఆధారంగా AI సూచనలు రూపొందిస్తోంది...',
  'AI Suggestions': 'AI సూచనలు',
  Regenerate: 'మళ్లీ రూపొందించండి',
  'Apply All': 'అన్నీ వర్తింపజేయండి',
  'Applying...': 'వర్తింపజేస్తోంది...',
  Apply: 'వర్తింపజేయండి',
  Uploading: 'అప్‌లోడ్ అవుతోంది',
  Uploaded: 'అప్‌లోడ్ అయింది',
  'Raw Material': 'ముడి పదార్థం',
  Stage: 'దశ',
  Director: 'డైరెక్టర్',
  Shareholder: 'వాటాదారు',
  Unit: 'యూనిట్',
  'Unit name': 'యూనిట్ పేరు',
  'Describe sensitivity analysis': 'సెన్సిటివిటీ విశ్లేషణను వివరించండి',
  'Enter power requirements': 'విద్యుత్ అవసరాలు నమోదు చేయండి',
  'Enter water requirements': 'నీటి అవసరాలు నమోదు చేయండి',
  'Enter manpower requirements': 'మానవశక్తి అవసరాలు నమోదు చేయండి',
};

export function useClusterFormText() {
  const { i18n } = useTranslation();
  const isTe = i18n.language.startsWith('te');
  return (en: string) => {
    if (!en) return en;
    if (!isTe) return en;
    return TE[en] || en;
  };
}
