import { SCHEME_FORM_TE } from '@/lib/individualDpr/schemeFormTe';
import { useTranslation } from 'react-i18next';

/** English UI string → Telugu. Missing keys fall back to English. */
const TE: Record<string, string> = {
  ...SCHEME_FORM_TE,
  'Cluster Name *': 'క్లస్టర్ పేరు *',
  'District *': 'జిల్లా *',
  'Location *': 'స్థలం *',
  'Geographical Spread': 'భౌగోళిక విస్తరణ',
  'Nature of Business': 'వ్యాపార స్వభావం',
  'Major Products': 'ప్రధాన ఉత్పత్తులు',
  'Enterprise Count': 'ఎంటర్‌ప్రైజ్‌ల సంఖ్య',
  Micro: 'మైక్రో',
  Small: 'చిన్న',
  Medium: 'మధ్యస్థ',
  'Age of Enterprises': 'ఎంటర్‌ప్రైజ్‌ల వయసు',
  '< 5 years': '5 సంవత్సరాల లోపు',
  '5-10 years': '5-10 సంవత్సరాలు',
  '> 10 years': '10 సంవత్సరాలు పైన',
  'Employment per Unit': 'యూనిట్‌కు ఉపాధి',
  '< 5 employees': '5 మంది లోపు',
  '5-10 employees': '5-10 మంది',
  '> 10 employees': '10 మంది పైన',
  'Investment per Unit (₹ Lakhs)': 'యూనిట్‌కు పెట్టుబడి (₹ లక్షలు)',
  'Turnover per Unit (₹ Lakhs)': 'యూనిట్‌కు టర్నోవర్ (₹ లక్షలు)',
  'Market Served (%)': 'సేవ చేసే మార్కెట్ (%)',
  Domestic: 'దేశీయ',
  Export: 'ఎగుమతి',
  'Sector / Industry Type': 'రంగం / పరిశ్రమ రకం',
  'Sector Description': 'రంగం వివరణ',
  'National Importance': 'జాతీయ ప్రాముఖ్యత',
  'State-level Importance': 'రాష్ట్ర స్థాయి ప్రాముఖ్యత',
  'Key Products': 'ప్రధాన ఉత్పత్తులు',
  'Add Product': 'ఉత్పత్తి జోడించండి',
  Geography: 'భౌగోళికం',
  Climate: 'వాతావరణం',
  Infrastructure: 'మౌలిక సదుపాయాలు',
  'Key Economic Activities': 'ప్రధాన ఆర్థిక కార్యకలాపాలు',
  'Raw Material Availability': 'ముడి పదార్థాల లభ్యత',
  'Raw Material Quantity': 'ముడి పదార్థాల పరిమాణం',
  'Industrial Infrastructure': 'పారిశ్రామిక మౌలిక సదుపాయాలు',
  Connectivity: 'కనెక్టివిటీ',
  Road: 'రోడ్డు',
  Rail: 'రైలు',
  Port: 'పోర్టు',
  'Year of Establishment': 'స్థాపన సంవత్సరం',
  'Cluster Evolution': 'క్లస్టర్ పరిణామం',
  'Present Activities': 'ప్రస్తుత కార్యకలాపాలు',
  'Type of Units': 'యూనిట్ల రకం',
  'Production Capacity': 'ఉత్పత్తి సామర్థ్యం',
  'Technology Level': 'సాంకేతిక స్థాయి',
  Stakeholders: 'వాటాదారులు',
  'Raw Materials': 'ముడి పదార్థాలు',
  'Add Raw Material': 'ముడి పదార్థం జోడించండి',
  'Intermediate Products': 'మధ్యంతర ఉత్పత్తులు',
  'Final Products': 'తుది ఉత్పత్తులు',
  'Add Final Product': 'తుది ఉత్పత్తి జోడించండి',
  'Value Addition Stages': 'విలువ జోడింపు దశలు',
  'Add Value Addition Stage': 'విలువ జోడింపు దశను జోడించండి',
  'Major Buyers': 'ప్రధాన కొనుగోలుదారులు',
  'Existing Demand': 'ప్రస్తుత డిమాండ్',
  'Demand-Supply Gap': 'డిమాండ్-సప్లై అంతరం',
  'Target Market': 'లక్ష్య మార్కెట్',
  'Competitor Analysis': 'పోటీ విశ్లేషణ',
  'Price Trends': 'ధరల ధోరణులు',
  'Export Potential': 'ఎగుమతి సామర్థ్యం',
  'Technology Gaps': 'సాంకేతిక అంతరాలు',
  'Infrastructure Gaps': 'మౌలిక సదుపాయాల అంతరాలు',
  'Skill Gaps': 'నైపుణ్య అంతరాలు',
  'Marketing Gaps': 'మార్కెటింగ్ అంతరాలు',
  'Financial Gaps': 'ఆర్థిక అంతరాలు',
  'Justification for Intervention': 'జోక్యానికి సమర్థన',
  Strengths: 'బలాలు',
  Weaknesses: 'బలహీనతలు',
  Opportunities: 'అవకాశాలు',
  Threats: 'ముప్పులు',
  'Intervention Type': 'జోక్యం రకం',
  'Select type': 'రకం ఎంచుకోండి',
  Hard: 'హార్డ్',
  Soft: 'సాఫ్ట్',
  Both: 'రెండూ',
  Description: 'వివరణ',
  Objectives: 'లక్ష్యాలు',
  'Add Objective': 'లక్ష్యం జోడించండి',
  'Expected Benefits': 'ఆశించిన ప్రయోజనాలు',
  Name: 'పేరు',
  Location: 'స్థలం',
  'Land Details': 'భూమి వివరాలు',
  'Civil Works': 'సివిల్ పనులు',
  'Manufacturing Process': 'తయారీ ప్రక్రియ',
  'Plant & Machinery': 'ప్లాంట్ మరియు యంత్రాలు',
  Capacity: 'సామర్థ్యం',
  'Power Requirements': 'విద్యుత్ అవసరాలు',
  'Water Requirements': 'నీటి అవసరాలు',
  'Manpower Requirements': 'మానవశక్తి అవసరాలు',
  'SPV Name': 'SPV పేరు',
  'Legal Status': 'చట్టపరమైన స్థితి',
  'Year of Incorporation': 'నమోదు సంవత్సరం',
  'Submitted To': 'సమర్పించిన సంస్థ',
  'Roles & Responsibilities': 'పాత్రలు మరియు బాధ్యతలు',
  'Board of Directors': 'డైరెక్టర్ల బోర్డు',
  'Add Director': 'డైరెక్టర్ జోడించండి',
  'Shareholding Pattern': 'వాటా నమూనా',
  'Add Shareholder': 'వాటాదారుని జోడించండి',
  'Member Units': 'సభ్య యూనిట్లు',
  'Add Member Unit': 'సభ్య యూనిట్ జోడించండి',
  'Statutory Registrations': 'చట్టబద్ధమైన నమోదులు',
  'Land (₹ Lakhs)': 'భూమి (₹ లక్షలు)',
  'Building (₹ Lakhs)': 'భవనం (₹ లక్షలు)',
  'Machinery (₹ Lakhs)': 'యంత్రాలు (₹ లక్షలు)',
  'Utilities & Infrastructure (₹ Lakhs)': 'యుటిలిటీలు & మౌలిక సదుపాయాలు (₹ లక్షలు)',
  'Preliminary & Pre-operative (₹ Lakhs)': 'ప్రాథమిక & ప్రీ-ఆపరేటివ్ (₹ లక్షలు)',
  'Working Capital Margin (₹ Lakhs)': 'వర్కింగ్ క్యాపిటల్ మార్జిన్ (₹ లక్షలు)',
  'Total Project Cost': 'మొత్తం ప్రాజెక్ట్ ఖర్చు',
  Lakhs: 'లక్షలు',
  'SPV Contribution (₹ Lakhs)': 'SPV వాటా (₹ లక్షలు)',
  'Government Grant (₹ Lakhs)': 'ప్రభుత్వ గ్రాంట్ (₹ లక్షలు)',
  'Bank Loan (₹ Lakhs)': 'బ్యాంకు రుణం (₹ లక్షలు)',
  'Other Sources (₹ Lakhs)': 'ఇతర వనరులు (₹ లక్షలు)',
  'Total Finance': 'మొత్తం నిధులు',
  'Raw Material Cost (₹ Lakhs)': 'ముడి పదార్థాల ఖర్చు (₹ లక్షలు)',
  'Power Cost (₹ Lakhs)': 'విద్యుత్ ఖర్చు (₹ లక్షలు)',
  'Wages (₹ Lakhs)': 'వేతనాలు (₹ లక్షలు)',
  'Maintenance (₹ Lakhs)': 'నిర్వహణ (₹ లక్షలు)',
  'Administrative Expenses (₹ Lakhs)': 'పరిపాలనా ఖర్చులు (₹ లక్షలు)',
  'Marketing Expenses (₹ Lakhs)': 'మార్కెటింగ్ ఖర్చులు (₹ లక్షలు)',
  'Annual Production Volume': 'వార్షిక ఉత్పత్తి పరిమాణం',
  'Annual Sales Realization (₹ Lakhs)': 'వార్షిక అమ్మకాలు (₹ లక్షలు)',
  'Basic Financial Indicators': 'ప్రాథమిక ఆర్థిక సూచికలు',
  'Break-even Point (₹ Lakhs)': 'బ్రేక్-ఈవెన్ పాయింట్ (₹ లక్షలు)',
  'IRR (%)': 'IRR (%)',
  'NPV (₹ Lakhs)': 'NPV (₹ లక్షలు)',
  'Sensitivity Analysis': 'సెన్సిటివిటీ విశ్లేషణ',
  'Start Date': 'ప్రారంభ తేదీ',
  'End Date': 'ముగింపు తేదీ',
  Milestones: 'మైలురాళ్లు',
  'Add Milestone': 'మైలురాయి జోడించండి',
  'Employment Generation': 'ఉపాధి సృష్టి',
  'Turnover Growth (%)': 'టర్నోవర్ వృద్ధి (%)',
  'Export Growth (%)': 'ఎగుమతి వృద్ధి (%)',
  'Income Enhancement (%)': 'ఆదాయ పెరుగుదల (%)',
  'Increase in Units': 'యూనిట్ల పెరుగుదల',
  'Sustainability Outcomes': 'సుస్థిర ఫలితాలు',
  'CFC Name': 'CFC పేరు',
  'Total Implementation Period': 'మొత్తం అమలు కాలం',
  'Building Estimates': 'భవన అంచనాలు',
  'Machinery Quotations': 'యంత్రాల కోటేషన్లు',
  'Member Registrations': 'సభ్య నమోదులు',
  'Building Plan': 'భవన ప్రణాళిక',
  'Quotations': 'కోటేషన్లు',
  'SPV Registration': 'SPV నమోదు',
  'Supporting Documents': 'సహాయక పత్రాలు',
  'Enter cluster name': 'క్లస్టర్ పేరు నమోదు చేయండి',
  'Enter district': 'జిల్లా నమోదు చేయండి',
  'Enter location': 'స్థలం నమోదు చేయండి',
  'Describe geographical spread': 'భౌగోళిక విస్తరణను వివరించండి',
  'Enter nature of business': 'వ్యాపార స్వభావం నమోదు చేయండి',
  'Enter major products': 'ప్రధాన ఉత్పత్తులు నమోదు చేయండి',
  'Enter sector type': 'రంగం రకం నమోదు చేయండి',
  'Describe the sector in detail': 'రంగాన్ని వివరంగా వర్ణించండి',
  'Describe national importance': 'జాతీయ ప్రాముఖ్యతను వివరించండి',
  'Describe state-level importance': 'రాష్ట్ర స్థాయి ప్రాముఖ్యతను వివరించండి',
  'Enter product name': 'ఉత్పత్తి పేరు నమోదు చేయండి',
  'Describe geography': 'భౌగోళికాన్ని వివరించండి',
  'Enter climate details': 'వాతావరణ వివరాలు నమోదు చేయండి',
  'Describe infrastructure': 'మౌలిక సదుపాయాలను వివరించండి',
  'Describe key economic activities': 'ప్రధాన ఆర్థిక కార్యకలాపాలను వివరించండి',
  'Describe raw material availability': 'ముడి పదార్థాల లభ్యతను వివరించండి',
  'Enter quantity': 'పరిమాణం నమోదు చేయండి',
  'Describe industrial infrastructure': 'పారిశ్రామిక మౌలిక సదుపాయాలను వివరించండి',
  'Enter road connectivity details': 'రోడ్డు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Enter rail connectivity details': 'రైలు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Enter port connectivity details': 'పోర్టు కనెక్టివిటీ వివరాలు నమోదు చేయండి',
  'Describe cluster evolution': 'క్లస్టర్ పరిణామాన్ని వివరించండి',
  'Describe present activities': 'ప్రస్తుత కార్యకలాపాలను వివరించండి',
  'Enter type of units': 'యూనిట్ల రకం నమోదు చేయండి',
  'Enter production capacity': 'ఉత్పత్తి సామర్థ్యం నమోదు చేయండి',
  'Enter technology level': 'సాంకేతిక స్థాయి నమోదు చేయండి',
  'Material name': 'పదార్థం పేరు',
  Source: 'మూలం',
  'Enter final product': 'తుది ఉత్పత్తి నమోదు చేయండి',
  'Stage name': 'దశ పేరు',
  'Enter SPV name': 'SPV పేరు నమోదు చేయండి',
  'Enter legal status': 'చట్టపరమైన స్థితి నమోదు చేయండి',
  'e.g., DIC, District': 'ఉదా: DIC, జిల్లా',
  'Activity name': 'కార్యకలాపం పేరు',
  'Separate multiple stakeholders with commas': 'బహుళ వాటాదారులను కామాలతో వేరు చేయండి',
  'Separate multiple products with commas': 'బహుళ ఉత్పత్తులను కామాలతో వేరు చేయండి',
  'Separate multiple buyers with commas': 'బహుళ కొనుగోలుదారులను కామాలతో వేరు చేయండి',
  'Separate multiple strengths with commas': 'బహుళ బలాలను కామాలతో వేరు చేయండి',
  'Separate multiple weaknesses with commas': 'బహుళ బలహీనతలను కామాలతో వేరు చేయండి',
  'Separate multiple opportunities with commas': 'బహుళ అవకాశాలను కామాలతో వేరు చేయండి',
  'Separate multiple threats with commas': 'బహుళ ముప్పులను కామాలతో వేరు చేయండి',
  'Separate multiple objectives with commas': 'బహుళ లక్ష్యాలను కామాలతో వేరు చేయండి',
  'Separate multiple benefits with commas': 'బహుళ ప్రయోజనాలను కామాలతో వేరు చేయండి',
  'Separate multiple roles with commas': 'బహుళ పాత్రలను కామాలతో వేరు చేయండి',
  'Separate multiple registrations with commas': 'బహుళ నమోదులను కామాలతో వేరు చేయండి',
  'Separate multiple outcomes with commas': 'బహుళ ఫలితాలను కామాలతో వేరు చేయండి',
  Designation: 'పదవి',
  'Share (%)': 'వాటా (%)',
  Registration: 'నమోదు',
  'Get AI Suggestions': 'AI సూచనలు పొందండి',
  'Get contextual recommendations based on your previous step data':
    'మునుపటి దశ డేటా ఆధారంగా సందర్భోచిత సిఫార్సులు పొందండి',
  'Generate Suggestions': 'సూచనలు రూపొందించండి',
  'Complete Step 1 first to get AI suggestions for this step.':
    'ఈ దశకు AI సూచనల కోసం ముందుగా దశ 1ని పూర్తి చేయండి.',
  'No suggestions available. Try generating again or fill in more fields.':
    'సూచనలు లేవు. మళ్లీ ప్రయత్నించండి లేదా మరిన్ని ఫీల్డ్‌లు నింపండి.',
  'Generating AI suggestions based on previous steps...': 'మునుపటి దశల ఆధారంగా AI సూచనలు రూపొందిస్తోంది...',
  'AI Suggestions': 'AI సూచనలు',
  Regenerate: 'మళ్లీ రూపొందించండి',
  'Apply All': 'అన్నీ వర్తింపజేయండి',
  'Applying...': 'వర్తింపజేస్తోంది...',
  Apply: 'వర్తింపజేయండి',
  Uploading: 'అప్‌లోడ్ అవుతోంది',
  Uploaded: 'అప్‌లోడ్ అయింది',
  'Raw Material': 'ముడి పదార్థం',
  Stage: 'దశ',
  Director: 'డైరెక్టర్',
  Shareholder: 'వాటాదారు',
  Unit: 'యూనిట్',
  'Unit name': 'యూనిట్ పేరు',
  'Describe sensitivity analysis': 'సెన్సిటివిటీ విశ్లేషణను వివరించండి',
  'Enter power requirements': 'విద్యుత్ అవసరాలు నమోదు చేయండి',
  'Enter water requirements': 'నీటి అవసరాలు నమోదు చేయండి',
  'Enter manpower requirements': 'మానవశక్తి అవసరాలు నమోదు చేయండి',
  'Unit / Project Name *': 'యూనిట్ / ప్రాజెక్ట్ పేరు *',
  'Enter unit or project name': 'యూనిట్ లేదా ప్రాజెక్ట్ పేరు నమోదు చేయండి',
  'Village / town / industrial park': 'గ్రామం / పట్టణం / పారిశ్రామిక పార్క్',
  'Generate the rest of this DPR with AI': 'ఈ DPR మిగిలిన దశలను AIతో నింపండి',
  'Generate all steps with AI': 'అన్ని దశలను AIతో నింపండి',
  'PM Vishwakarma details': 'పీఎం విశ్వకర్మ వివరాలు',
  'Craft / trade': 'వృత్తి / కళ',
  'Select your craft': 'మీ వృత్తిని ఎంచుకోండి',
  'Current tools': 'ప్రస్తుత పనిముట్లు',
  'Tools you use today': 'మీరు ఇప్పుడు వాడే పనిముట్లు',
  'New tools needed (₹15,000 voucher)': 'కావాల్సిన కొత్త పనిముట్లు (₹15,000 వోచర్)',
  'Tools you want to buy with the voucher': 'వోచర్‌తో కొనాలనుకునే పనిముట్లు',
  'PM SVANidhi details': 'పీఎం స్వనిధి వివరాలు',
  'Vending proof': 'విక్రయ రుజువు',
  Select: 'ఎంచుకోండి',
  'Certificate of Vending (CoV)': 'వెండింగ్ సర్టిఫికేట్ (CoV)',
  'Letter of Recommendation (LoR)': 'సిఫార్సు పత్రం (LoR)',
  'UPI QR code': 'UPI QR కోడ్',
  'UPI ID or QR details': 'UPI ID లేదా QR వివరాలు',
  'FSSAI status': 'FSSAI స్థితి',
  'Already have FSSAI': 'FSSAI ఇప్పటికే ఉంది',
  'Will obtain / draft FSSAI': 'FSSAI తీసుకుంటాను / డ్రాఫ్ట్',
  'APIIC industrial park': 'APIIC పారిశ్రామిక పార్క్',
  'Is the unit inside an APIIC park?': 'యూనిట్ APIIC పార్క్‌లో ఉందా?',
  'Yes — land rebate may apply': 'అవును — భూమి రాయితీ వర్తించవచ్చు',
  No: 'కాదు',
  'How your unit evolved': 'మీ యూనిట్ ఎలా ఎదిగింది',
  'Describe how the unit evolved': 'యూనిట్ ఎలా ఎదిగిందో వివరించండి',
  'Type of unit': 'యూనిట్ రకం',
  'Unit / shed / workplace name': 'యూనిట్ / షెడ్ / కార్యస్థలం పేరు',
  'Mudra Nayak working capital': 'ముద్ర నాయక్ వర్కింగ్ క్యాపిటల్',
  'DSCR (profit + depreciation vs EMI)': 'DSCR (లాభం + తరుగుదల vs EMI)',
  '8th-pass / education certificate': '8వ తరగతి / విద్యా సర్టిఫికేట్',
  'Know which scheme you want? Vanilla bank term loan': 'పథకం తెలుసా? సాధారణ బ్యాంకు టర్మ్ లోన్',
  'Vanilla bank term loan': 'సాధారణ బ్యాంకు టర్మ్ లోన్',
  'PM Vishwakarma': 'పీఎం విశ్వకర్మ',
  'PM SVANidhi': 'పీఎం స్వనిధి',
  'Step list drops 15, 16, 17 (15 steps instead of 18).': 'దశల జాబితా 15, 16, 17ని తీసివేస్తుంది (18కి బదులు 15).',
  'Step 1 adds craft + current/new tools (₹15,000 voucher).': 'దశ 1లో వృత్తి + ప్రస్తుత/కొత్త పనిముట్లు (₹15,000 వోచర్) జోడవుతాయి.',
  'Step 18 uploads: Aadhaar, passbook, ration card.': 'దశ 18 అప్‌లోడ్లు: ఆధార్, పాస్‌బుక్, రేషన్ కార్డు.',
  'Step list drops 15, 16, 17.': 'దశల జాబితా 15, 16, 17ని తీసివేస్తుంది.',
  'Step 1 adds CoV vs LoR and UPI QR.': 'దశ 1లో CoV vs LoR మరియు UPI QR జోడవుతాయి.',
  'Step 18 upload: CoV or Letter of Recommendation.': 'దశ 18 అప్‌లోడ్: CoV లేదా సిఫార్సు పత్రం.',
  'Steps 1–17 stay the same length.': 'దశలు 1–17 పొడవు మారదు.',
  'Step 1 adds FSSAI yes/planned.': 'దశ 1లో FSSAI అవును/ప్రణాళిక జోడవుతుంది.',
  'Step 18 uploads: quotations, premises lease, draft FSSAI.': 'దశ 18 అప్‌లోడ్లు: కోటేషన్లు, ప్రాంగణం లీజు, డ్రాఫ్ట్ FSSAI.',
  'All 18 steps. No scheme extras on step 1.': 'అన్ని 18 దశలు. దశ 1లో పథక అదనపు ఫీల్డ్‌లు లేవు.',
  'Step 18: Aadhaar/PAN, Udyam, passbook, machinery quotations.': 'దశ 18: ఆధార్/PAN, ఉద్యమ్, పాస్‌బుక్, యంత్రాల కోటేషన్లు.',
  'No extra fields on steps 1–17 for this scheme in v1.': 'ఈ పథకానికి v1లో దశలు 1–17పై అదనపు ఫీల్డ్‌లు లేవు.',
  'Step 18 uses the default individual upload list (Aadhaar/PAN, Udyam, passbook, quotations).': 'దశ 18 డిఫాల్ట్ వ్యక్తిగత అప్‌లోడ్ జాబితా వాడుతుంది (ఆధార్/PAN, ఉద్యమ్, పాస్‌బుక్, కోటేషన్లు).',
  'Core questions on steps 1–17 do not change.': 'దశలు 1–17లోని ప్రధాన ప్రశ్నలు మారవు.',
  'Step 18 uploads: machinery quotes, building estimate (caste cert if SC/ST/BC from VentureMatch).': 'దశ 18 అప్‌లోడ్లు: యంత్రాల కోట్లు, భవన అంచనా (VentureMatch నుండి SC/ST/BC అయితే కుల సర్టిఫికేట్).',
  '8th-pass upload appears on step 18 if project cost is above the PMEGP education gate.': 'ప్రాజెక్ట్ ఖర్చు PMEGP విద్యా పరిమితి మించితే దశ 18లో 8వ తరగతి అప్‌లోడ్ కనిపిస్తుంది.',
  'Step 12 hides land/building tables only if VentureMatch budget is under ₹5L (Shishu/Kishore).': 'VentureMatch బడ్జెట్ ₹5 లక్షల లోపు (శిశు/కిషోర్) అయితేనే దశ 12 భూమి/భవన పట్టికలను దాచుతుంది.',
  'Step 15 shows Nayak WC (20% of turnover, 5% margin) for that same budget band.': 'దశ 15 అదే బడ్జెట్ బ్యాండ్‌కు నాయక్ WC (టర్నోవర్‌లో 20%, 5% మార్జిన్) చూపిస్తుంది.',
  'Step 18: shop proof, bank statements, quotes (+ Mudra closure if Tarun Plus).': 'దశ 18: దుకాణ రుజువు, బ్యాంకు స్టేట్‌మెంట్లు, కోట్లు (+ తరుణ్ ప్లస్ అయితే ముద్ర క్లోజర్).',
  'Step 1 asks if the unit is in an APIIC park (land-rebate hint).': 'దశ 1 యూనిట్ APIIC పార్క్‌లో ఉందో అడుగుతుంది (భూమి రాయితీ సూచన).',
  'Step 12 keeps land / building / P&M (FCI).': 'దశ 12 భూమి / భవనం / P&M (FCI) ఉంచుతుంది.',
  'Step 18: land/shed, CFE/CFO, CA FCI statement.': 'దశ 18: భూమి/షెడ్, CFE/CFO, CA FCI స్టేట్‌మెంట్.',
  'Uses the unit name, district, and location to fill every visible step except document uploads. You can edit anything afterwards.':
    'యూనిట్ పేరు, జిల్లా, స్థలం ఉపయోగించి డాక్యుమెంట్ అప్‌లోడ్లు తప్ప అన్ని కనిపించే దశలను నింపుతుంది. తర్వాత ఏదైనా సవరించవచ్చు.',
  Aadhaar: 'ఆధార్',
  'Savings Bank Passbook': 'సేవింగ్స్ బ్యాంకు పాస్‌బుక్',
  'Ration Card (family verification)': 'రేషన్ కార్డు (కుటుంబ ధృవీకరణ)',
  'Certificate of Vending (CoV) or Letter of Recommendation': 'వెండింగ్ సర్టిఫికేట్ (CoV) లేదా సిఫార్సు పత్రం',
  'Aadhaar / PAN': 'ఆధార్ / PAN',
  'Udyam Certificate': 'ఉద్యమ్ సర్టిఫికేట్',
  'Bank Passbook': 'బ్యాంకు పాస్‌బుక్',
  'Machinery / Equipment Quotations': 'యంత్రాల / పరికరాల కోటేషన్లు',
  Question: 'ప్రశ్న',
  Answer: 'సమాధానం',
  Section: 'విభాగం',
  Document: 'పత్రం',
  Status: 'స్థితి',
  Pending: 'పెండింగ్',
  On: 'పై',
  'Table of Contents': 'విషయ సూచిక',
};

export function useClusterFormText() {
  const { i18n } = useTranslation();
  const isTe = i18n.language.startsWith('te');
  return (en: string) => {
    if (!en) return en;
    if (!isTe) return en;
    return TE[en] || en;
  };
}
