/** Telugu labels for BUSINESS_SKILLS (store stays English). */
export const BUSINESS_SKILLS_TE: Record<string, string> = {
  'Pottery': 'కుమ్మరి / కుండల తయారీ',
  'Carpentry': 'వడ్రంగి పని',
  'Blacksmithing': 'కమ్మరి పని',
  'Goldsmithing / jewellery': 'కంసాలి / ఆభరణాలు',
  'Tailoring / stitching': 'టైలరింగ్ / కుట్టు పని',
  'Cobbling / footwear': 'చెప్పులు / పాదరక్షలు',
  'Masonry / construction labour': 'రాజమిస్త్రి / నిర్మాణ శ్రమ',
  'Basket / mat / broom making': 'బుట్ట / చాప / చీపురు తయారీ',
  'Coir products': 'కొయిర్ ఉత్పత్తులు',
  'Handloom weaving': 'చేనేత నేత',
  'Powerloom / textile weaving': 'పవర్‌లూమ్ / వస్త్ర నేత',
  'Doll / toy making': 'బొమ్మలు / టాయ్ తయారీ',
  'Garland / flower work': 'మాలలు / పూల పని',
  'Barber / salon': 'మంగలి / సెలూన్',
  'Laundry / washing': 'ధోబీ / వాషింగ్',
  'Fishing net making': 'చేపల వల తయారీ',
  'Stone carving / sculpture': 'రాతి చెక్కడం / శిల్పం',
  'Boat making': 'పడవ తయారీ',
  'Locksmith': 'తాళాలు / కీలు',
  'Tool / hammer kit making': 'పనిముట్లు / సుత్తి కిట్ తయారీ',
  'Food processing': 'ఆహార ప్రాసెసింగ్',
  'Bakery / confectionery': 'బేకరీ / మిఠాయి',
  'Catering / tiffin service': 'క్యాటరింగ్ / టిఫిన్ సేవ',
  'Street food / food stall': 'స్ట్రీట్ ఫుడ్ / ఫుడ్ స్టాల్',
  'Dairy / milk products': 'పాల / పాల ఉత్పత్తులు',
  'Poultry / egg business': 'కోడి / గుడ్ల వ్యాపారం',
  'Fish / seafood trade': 'చేపలు / సీఫుడ్ వ్యాపారం',
  'Oil mill / oil extraction': 'నూనె మిల్లు',
  'Rice / flour mill': 'బియ్యం / పిండి మిల్లు',
  'Spice / pickle processing': 'మసాలా / ఊరగాయ ప్రాసెసింగ్',
  'Fruit / vegetable processing': 'పండ్లు / కూరగాయల ప్రాసెసింగ్',
  'Kirana / general store': 'కిరాణా / జనరల్ స్టోర్',
  'Vegetable / fruit vending': 'కూరగాయలు / పండ్ల అమ్మకం',
  'Cloth / garment retail': 'బట్టలు / వస్త్ర రిటైల్',
  'Mobile / electronics retail': 'మొబైల్ / ఎలక్ట్రానిక్స్ రిటైల్',
  'Stationery / book shop': 'స్టేషనరీ / పుస్తకాల దుకాణం',
  'Medical / pharmacy retail': 'మెడికల్ / ఫార్మసీ',
  'Hardware / building materials retail': 'హార్డ్‌వేర్ / నిర్మాణ సామగ్రి',
  'Automobile spare parts retail': 'వాహన స్పేర్ పార్ట్స్',
  'Wholesale trading': 'హోల్‌సేల్ వ్యాపారం',
  'Beauty parlour / cosmetics': 'బ్యూటీ పార్లర్ / కాస్మెటిక్స్',
  'Photography / videography': 'ఫోటోగ్రఫీ / వీడియోగ్రఫీ',
  'Printing / Xerox / DTP': 'ప్రింటింగ్ / జిరాక్స్ / DTP',
  'Computer / IT services': 'కంప్యూటర్ / IT సేవలు',
  'Mobile repairing': 'మొబైల్ రిపేరింగ్',
  'Two-wheeler / auto repairing': 'టూ-వీలర్ / ఆటో రిపేరింగ్',
  'Electrical repairing': 'ఎలక్ట్రికల్ రిపేరింగ్',
  'Plumbing / electrical contracting': 'ప్లంబింగ్ / ఎలక్ట్రికల్ కాంట్రాక్టింగ్',
  'Transport / logistics': 'రవాణా / లాజిస్టిక్స్',
  'Auto / taxi / transport service': 'ఆటో / టాక్సీ / రవాణా సేవ',
  'Tuition / coaching': 'ట్యూషన్ / కోచింగ్',
  'Day care / creche': 'డే కేర్ / క్రెచ్',
  'Security services': 'సెక్యూరిటీ సేవలు',
  'Housekeeping / facility services': 'హౌస్‌కీపింగ్ / ఫెసిలిటీ సేవలు',
  'Fabrication / welding': 'ఫ్యాబ్రికేషన్ / వెల్డింగ్',
  'Furniture making': 'ఫర్నిచర్ తయారీ',
  'Plastic products': 'ప్లాస్టిక్ ఉత్పత్తులు',
  'Paper / packaging products': 'కాగితం / ప్యాకేజింగ్ ఉత్పత్తులు',
  'Brick / cement products': 'ఇటుక / సిమెంట్ ఉత్పత్తులు',
  'Agarbatti / incense making': 'అగరబత్తి తయారీ',
  'Candle / soap making': 'కొవ్వొత్తి / సబ్బు తయారీ',
  'Garment manufacturing': 'వస్త్ర తయారీ',
  'Leather products': 'లెదర్ ఉత్పత్తులు',
  'Metal fabrication': 'మెటల్ ఫ్యాబ్రికేషన్',
  'Engineering workshop': 'ఇంజనీరింగ్ వర్క్‌షాప్',
  'Pharmaceuticals / chemicals (MSME)': 'ఫార్మా / కెమికల్స్ (MSME)',
  'Nursery / gardening': 'నర్సరీ / తోటపని',
  'Animal husbandry': 'పశుసంవర్ధకం',
  'Beekeeping / honey': 'తేనెటీగలు / తేనె',
  'Handicrafts (general)': 'హస్తకళలు (సాధారణ)',
  'Event decoration / mandap': 'ఈవెంట్ అలంకరణ / మండపం',
  'Recycling / scrap trading': 'రీసైక్లింగ్ / స్క్రాప్ వ్యాపారం',
  'E-commerce / online selling': 'ఈ-కామర్స్ / ఆన్‌లైన్ అమ్మకం',
  'Other manufacturing': 'ఇతర తయారీ',
  'Other services': 'ఇతర సేవలు',
  'Other trade / retail': 'ఇతర వ్యాపారం / రిటైల్',
};

