/** Telugu for Latest DPR / cluster form labels that were still falling back to English. */
export const FORM_FIELD_TE: Record<string, string> = {
  District: 'జిల్లా',
  Step: 'దశ',
  'Financial projections': 'ఆర్థిక అంచనాలు',
  'Financial projections (actuals and estimates)': 'ఆర్థిక అంచనాలు (గత సంవత్సరాలు మరియు అంచనాలు)',
  'Financial projections — previous years and estimates (₹ Lakhs)':
    'ఆర్థిక అంచనాలు — గత సంవత్సరాలు మరియు అంచనాలు (₹ లక్షలు)',
  'Rs. In Lakhs': 'రూ. లక్షల్లో',
  Previous: 'గత',
  Projected: 'అంచనా',
  Particulars: 'వివరాలు',
  'Sl. No.': 'క్ర.సం.',
  'Sales realisation': 'అమ్మకాల వసూలు',
  'Raw material': 'ముడి పదార్థం',
  Promoters: 'ప్రమోటర్లు',
  "Father's / husband's name": 'తండ్రి / భర్త పేరు',
  'Date of birth': 'పుట్టిన తేదీ',
  'Experience (years)': 'అనుభవం (సంవత్సరాలు)',
  'Residential address': 'నివాస చిరునామా',
  'Add promoter': 'ప్రమోటర్ జోడించండి',
  'Cost already incurred and still to be incurred': 'ఇప్పటికే ఖర్చు చేసినది మరియు ఇంకా ఖర్చు చేయబోయేది',
  'Cost already incurred and still to be incurred (₹ Lakhs)': 'ఇప్పటికే ఖర్చు చేసినది మరియు ఇంకా ఖర్చు చేయబోయేది (₹ లక్షలు)',
  'Amounts are ₹ Lakhs.': 'మొత్తాలు ₹ లక్షల్లో.',
  'Already incurred': 'ఇప్పటికే ఖర్చు',
  'To be incurred': 'ఇంకా ఖర్చు',
  'Building / shed': 'భవనం / షెడ్',
  'Machinery / equipment': 'యంత్రాలు / పరికరాలు',
  'Furniture and fixtures': 'ఫర్నిచర్ మరియు ఫిక్చర్లు',
  'Furniture and fixtures (₹ Lakhs)': 'ఫర్నిచర్ మరియు ఫిక్చర్లు (₹ లక్షలు)',
  'Security deposits': 'సెక్యూరిటీ డిపాజిట్లు',
  'Security deposits (₹ Lakhs)': 'సెక్యూరిటీ డిపాజిట్లు (₹ లక్షలు)',
  'Machinery list': 'యంత్రాల జాబితా',
  'Add machinery': 'యంత్రం జోడించండి',
  'Unit cost (₹ Lakhs)': 'యూనిట్ ధర (₹ లక్షలు)',
  Used: 'వాడిన',
  'Term loan and subsidy terms': 'టర్మ్ లోన్ మరియు సబ్సిడీ నిబంధనలు',
  'Cash credit / working capital limit (₹ Lakhs)': 'క్యాష్ క్రెడిట్ / వర్కింగ్ క్యాపిటల్ పరిమితి (₹ లక్షలు)',
  'Bank name': 'బ్యాంకు పేరు',
  'Interest rate (% per year)': 'వడ్డీ రేటు (సంవత్సరానికి %)',
  'Moratorium (months)': 'మారటోరియం (నెలలు)',
  'Loan tenure (months)': 'రుణ కాలం (నెలలు)',
  'Subsidy rate (%)': 'సబ్సిడీ రేటు (%)',
  'Projection assumptions': 'అంచనా ఊహలు',
  'Installed capacity per day': 'రోజుకు స్థాపిత సామర్థ్యం',
  'Working days in a year': 'సంవత్సరంలో పని దినాలు',
  'Capacity utilisation (%)': 'సామర్థ్య వినియోగం (%)',
  'Selling price per unit (₹)': 'యూనిట్ అమ్మకపు ధర (₹)',
  'Rent per month (₹)': 'నెలకు అద్దె (₹)',
  'Salaries per month (₹)': 'నెలకు జీతాలు (₹)',
  'Power per month (₹)': 'నెలకు విద్యుత్ (₹)',
  'Annual expense increase (%)': 'వార్షిక ఖర్చు పెరుగుదల (%)',
  'Repayment summary': 'తిరిగి చెల్లింపు సారాంశం',
  'Term loan (₹ Lakhs)': 'టర్మ్ లోన్ (₹ లక్షలు)',
  'Indicative EMI (₹ Lakhs)': 'సూచన EMI (₹ లక్షలు)',
  'Break-even': 'బ్రేక్ ఈవెన్',
  'Break-even sales (₹ Lakhs)': 'బ్రేక్ ఈవెన్ అమ్మకాలు (₹ లక్షలు)',
  'Break-even capacity (%)': 'బ్రేక్ ఈవెన్ సామర్థ్యం (%)',
  'Average DSCR': 'సగటు DSCR',
  'Opening WDV': 'ప్రారంభ WDV',
  Additions: 'జోడింపులు',
  'Depreciation for the year': 'సంవత్సరపు తరుగుదల',
  'Closing WDV': 'ముగింపు WDV',
  Salaries: 'జీతాలు',
  'Administrative expenses': 'పరిపాలన ఖర్చులు',
  'Income tax': 'ఆదాయపు పన్ను',
  'Depreciation, DSCR, break-even and repayment': 'తరుగుదల, DSCR, బ్రేక్ ఈవెన్ మరియు తిరిగి చెల్లింపు',
  'Enter actuals for the three previous financial years and estimates for the next five. All figures are ₹ Lakhs.':
    'గత మూడు ఆర్థిక సంవత్సరాల వాస్తవాలు మరియు తర్వాతి ఐదు సంవత్సరాల అంచనాలు నమోదు చేయండి. అన్ని సంఖ్యలు ₹ లక్షల్లో.',
  'Fill the required fields before continuing': 'కొనసాగే ముందు తప్పనిసరి ఫీల్డ్‌లను నింపండి',
  'Dev mode': 'డెవ్ మోడ్',
  'Urban or rural': 'పట్టణం లేదా గ్రామీణం',
  Urban: 'పట్టణం',
  Rural: 'గ్రామీణం',
  'EDP training': 'EDP శిక్షణ',
  'EDP completed': 'EDP పూర్తయింది',
  'EDP still pending': 'EDP ఇంకా పెండింగ్',
  'Earlier government subsidy': 'ఇంతకు ముందు ప్రభుత్వ సబ్సిడీ',
  'Only one person in the family for this scheme': 'ఈ పథకానికి కుటుంబంలో ఒక్క వ్యక్తి మాత్రమే',
  'Products, share of output and selling price': 'ఉత్పత్తులు, వాటా మరియు అమ్మకపు ధర',
  'Add product': 'ఉత్పత్తిని జోడించండి',
  Product: 'ఉత్పత్తి',
  'Share of output (%)': 'ఉత్పత్తి వాటా (%)',
  'Selling price (₹)': 'అమ్మకపు ధర (₹)',
  'Number of looms / machines': 'మగ్గాలు / యంత్రాల సంఖ్య',
  'Shifts per day': 'రోజుకు షిఫ్టులు',
  'Raw materials': 'ముడి సరుకు',
  'Add raw material': 'ముడి సరుకును జోడించండి',
  Material: 'సరుకు',
  Use: 'వాడుక',
  'How it is bought': 'ఎలా కొనుగోలు చేస్తారు',
  'Staff by role and monthly pay': 'పాత్ర వారీగా సిబ్బంది మరియు నెల జీతం',
  'Add role': 'పాత్రను జోడించండి',
  Role: 'పాత్ర',
  'Number of people': 'వ్యక్తుల సంఖ్య',
  'Monthly pay (₹)': 'నెల జీతం (₹)',
  'Workshop area (sq.ft.)': 'వర్క్‌షాప్ విస్తీర్ణం (చ.అ.)',
  'Production floor (sq.ft.)': 'ఉత్పత్తి అంతస్తు (చ.అ.)',
  'Storage / packing area (sq.ft.)': 'నిల్వ / ప్యాకింగ్ విస్తీర్ణం (చ.అ.)',
  'Office area (sq.ft.)': 'కార్యాలయ విస్తీర్ణం (చ.అ.)',
  'Lease period (years)': 'లీజు కాలం (సంవత్సరాలు)',
  'Water use and dye wastewater': 'నీటి వాడకం మరియు డై మురుగు',
  'Working capital buildup': 'నిర్వహణ మూలధనం లెక్క',
  'Stock, work in progress, finished goods, receivables and cash, less supplier credit.':
    'స్టాక్, పనిలో ఉన్నవి, పూర్తయిన వస్తువులు, రావాల్సిన బాకీలు మరియు నగదు, సరఫరాదారు క్రెడిట్ తీసివేసి.',
  'Raw material stock (₹ Lakhs)': 'ముడి సరుకు స్టాక్ (₹ లక్షలు)',
  'Work in progress (₹ Lakhs)': 'పనిలో ఉన్నవి (₹ లక్షలు)',
  'Finished goods (₹ Lakhs)': 'పూర్తయిన వస్తువులు (₹ లక్షలు)',
  'Receivables (₹ Lakhs)': 'రావాల్సిన బాకీలు (₹ లక్షలు)',
  'Supplier credit (₹ Lakhs)': 'సరఫరాదారు క్రెడిట్ (₹ లక్షలు)',
  'Cash (₹ Lakhs)': 'నగదు (₹ లక్షలు)',
  'GST (₹ Lakhs)': 'GST (₹ లక్షలు)',
  'Transport (₹ Lakhs)': 'రవాణా (₹ లక్షలు)',
  'Installation (₹ Lakhs)': 'అమర్పు (₹ లక్షలు)',
  'Expected life (years)': 'అంచనా జీవితం (సంవత్సరాలు)',
  'Yearly maintenance (₹ Lakhs)': 'వార్షిక నిర్వహణ (₹ లక్షలు)',
  'Term loan terms': 'టర్మ్ లోన్ నిబంధనలు',
  'Capacity utilisation by projected year': 'అంచనా సంవత్సరం వారీగా సామర్థ్య వినియోగం',
  'Risks and how they will be handled': 'నష్టాలు మరియు వాటిని ఎలా ఎదుర్కొంటారు',
  'Add risk': 'నష్టాన్ని జోడించండి',
  Risk: 'నష్టం',
  'How it will be handled': 'ఎలా ఎదుర్కొంటారు',
  'Education certificate': 'విద్యా ధృవీకరణ పత్రం',
  'EDP certificate': 'EDP ధృవీకరణ పత్రం',
  'Lease deed / premises proof': 'లీజు దస్తావేజు / ప్రాంగణ రుజువు',
  'Yarn, dye and packing rate sheets': 'నూలు, రంగు మరియు ప్యాకింగ్ ధరల పట్టికలు',
  'Dealer enquiries or purchase orders': 'డీలర్ విచారణలు లేదా కొనుగోలు ఆర్డర్లు',
  '51% Controlling Stake Proof (if not sole proprietor)':
    '51% నియంత్రణ వాటా రుజువు (ఏకైక యజమాని కాకపోతే)',
  '51% SC/ST Shareholding Proof (if not sole proprietor)':
    '51% SC/ST వాటా రుజువు (ఏకైక యజమాని కాకపోతే)',
  'AP CMEP': 'AP CMEP',
  'AP Domicile Proof': 'AP నివాస రుజువు',
  'AP EDP capital subsidy (₹ Lakhs) — % of FCI by size':
    'AP EDP మూలధన సబ్సిడీ (₹ లక్షలు) — పరిమాణం ప్రకారం FCI శాతం',
  'AP FPP 4.0': 'AP FPP 4.0',
  'AP MSME-EDP 4.0': 'AP MSME-EDP 4.0',
  'AP MSME-PARKS': 'AP MSME-PARKS',
  'AP OBMMS': 'AP OBMMS',
  'AP Technology Upgradation': 'AP సాంకేతిక అప్‌గ్రేడేషన్',
  'AP tech-upgrade subsidy (₹ Lakhs) — % of FCI by size':
    'AP టెక్-అప్‌గ్రేడ్ సబ్సిడీ (₹ లక్షలు) — పరిమాణం ప్రకారం FCI శాతం',
  'APIIC / Park Allotment Application': 'APIIC / పార్క్ కేటాయింపు దరఖాస్తు',
  'Activity type': 'కార్యకలాప రకం',
  'Applicant / firm name': 'దరఖాస్తుదారు / సంస్థ పేరు',
  'Bank Passbook / Cancelled Cheque': 'బ్యాంకు పాస్‌బుక్ / రద్దు చెక్',
  'Bank Passbook / Sanction Path': 'బ్యాంకు పాస్‌బుక్ / మంజూరు మార్గం',
  'Bank Statements': 'బ్యాంకు స్టేట్‌మెంట్లు',
  'Bank composite loan TL + WC (₹ Lakhs)': 'బ్యాంకు కాంపోజిట్ రుణం TL + WC (₹ లక్షలు)',
  'Bank term loan + / or WC (₹ Lakhs)': 'బ్యాంకు టర్మ్ లోన్ మరియు / లేదా WC (₹ లక్షలు)',
  'Bank term loan for P&M (₹ Lakhs)': 'P&M కోసం బ్యాంకు టర్మ్ లోన్ (₹ లక్షలు)',
  'Break-even (capacity %)': 'బ్రేక్-ఈవెన్ (సామర్థ్యం %)',
  'Brief location / market catchment': 'సంక్షిప్త స్థలం / మార్కెట్ పరిధి',
  'Building / Workshed Estimate': 'భవనం / వర్క్‌షెడ్ అంచనా',
  'Building / shed (₹ Lakhs)': 'భవనం / షెడ్ (₹ లక్షలు)',
  'Building Estimate / Premises Lease': 'భవన అంచనా / ప్రాంగణ లీజు',
  'CA Certificate of Existing FCI': 'ఉన్న FCI యొక్క CA సర్టిఫికేట్',
  'CA Certificate of Existing Investment': 'ఉన్న పెట్టుబడి యొక్క CA సర్టిఫికేట్',
  'CA FCI Statement': 'CA FCI స్టేట్‌మెంట్',
  'CA Statement of Upgrade FCI': 'అప్‌గ్రేడ్ FCI యొక్క CA స్టేట్‌మెంట్',
  'CA Turnover Certificate': 'CA టర్నోవర్ సర్టిఫికేట్',
  'CA-certified FCI Statement': 'CA ధృవీకరించిన FCI స్టేట్‌మెంట్',
  'CFE / CFO': 'CFE / CFO',
  'CGTMSE (MUDRA-adjacent)': 'CGTMSE (ముద్ర-సంబంధిత)',
  'Cancelled Cheque': 'రద్దు చెక్',
  'Capacity / throughput': 'సామర్థ్యం / ఉత్పత్తి రేటు',
  'Capacity / throughput (if applicable)': 'సామర్థ్యం / ఉత్పత్తి రేటు (వర్తిస్తే)',
  'Caste / Corporation Eligibility Proof': 'కులం / కార్పొరేషన్ అర్హత రుజువు',
  'Caste / Special-category Certificate': 'కులం / ప్రత్యేక వర్గం సర్టిఫికేట్',
  'Caste Certificate': 'కుల ధృవీకరణ పత్రం',
  'Caste Certificate (SC / ST)': 'కుల ధృవీకరణ పత్రం (SC / ST)',
  'Certificate of Vending / Vendor ID or Portal LoR':
    'వెండింగ్ సర్టిఫికేట్ / విక్రేత ID లేదా పోర్టల్ సిఫార్సు',
  'Coir Board Documents': 'కొబ్బరి బోర్డు పత్రాలు',
  'Coir Vikas Yojana': 'కొబ్బరి వికాస్ యోజన',
  'Commercial production date (CoD)': 'వాణిజ్య ఉత్పత్తి తేదీ (CoD)',
  'Competitive LEAN': 'పోటీ LEAN',
  'Concept / Innovation Note': 'భావన / ఆవిష్కరణ నోట్',
  'Controlling stake %': 'నియంత్రణ వాటా %',
  'Correspondence address': 'ఉత్తరప్రత్యుత్తర చిరునామా',
  'Demand / footfall note': 'డిమాండ్ / రాకపోకల గమనిక',
  'Direct employment (count)': 'ప్రత్యక్ష ఉపాధి (సంఖ్య)',
  'ECLGS 5.0': 'ECLGS 5.0',
  'ECLGS working-capital term loan (₹ Lakhs)': 'ECLGS వర్కింగ్ క్యాపిటల్ టర్మ్ లోన్ (₹ లక్షలు)',
  'EE Equipment Quotations': 'EE పరికరాల కోటేషన్లు',
  'EPM Niryat Protsahan': 'EPM నిర్యాత్ ప్రోత్సాహన్',
  'Enterprise development loan tranche (₹ Lakhs)': 'సంస్థ అభివృద్ధి రుణ విడత (₹ లక్షలు)',
  'Existing Sanction Letter': 'ఉన్న మంజూరు లేఖ',
  'Expected annual turnover (₹ Lakhs)': 'అంచనా వార్షిక టర్నోవర్ (₹ లక్షలు)',
  'FSSAI Licence': 'FSSAI లైసెన్స్',
  'FSSAI Licence / Draft Registration': 'FSSAI లైసెన్స్ / డ్రాఫ్ట్ నమోదు',
  'Failed to upload document': 'పత్రం అప్‌లోడ్ విఫలమైంది',
  'Firm / proprietor name': 'సంస్థ / యజమాని పేరు',
  'Furniture & fixtures (₹ Lakhs)': 'ఫర్నిచర్ మరియు ఫిక్చర్లు (₹ లక్షలు)',
  'GST Returns / ITR': 'GST రిటర్న్లు / ITR',
  'Government grant (₹ Lakhs) — usually 0 (guarantee ≠ capital)':
    'ప్రభుత్వ గ్రాంట్ (₹ లక్షలు) — సాధారణంగా 0 (హామీ మూలధనం కాదు)',
  'Government grant (₹ Lakhs) — usually 0 for MUDRA':
    'ప్రభుత్వ గ్రాంట్ (₹ లక్షలు) — ముద్రకు సాధారణంగా 0',
  'How the unit evolved': 'యూనిట్ ఎలా ఎదిగింది',
  'IEC Certificate': 'IEC సర్టిఫికేట్',
  'Installed / proposed capacity': 'ఏర్పాటు / ప్రతిపాదిత సామర్థ్యం',
  'Land / FCI land (₹ Lakhs)': 'భూమి / FCI భూమి (₹ లక్షలు)',
  'Land / Premises Lease or Ownership Proof': 'భూమి / ప్రాంగణ లీజు లేదా యాజమాన్య రుజువు',
  'Land / Shed Allotment or Lease': 'భూమి / షెడ్ కేటాయింపు లేదా లీజు',
  'Land / building / workshed — building (₹ Lakhs)': 'భూమి / భవనం / వర్క్‌షెడ్ — భవనం (₹ లక్షలు)',
  'Land / building / workshed — land (₹ Lakhs)': 'భూమి / భవనం / వర్క్‌షెడ్ — భూమి (₹ లక్షలు)',
  'Land Documents': 'భూమి పత్రాలు',
  'Last 3 Years Profit / ITR Statements': 'గత 3 సంవత్సరాల లాభం / ITR స్టేట్‌మెంట్లు',
  'Legal status': 'చట్టబద్ధ స్థితి',
  'Legal status (sole / partnership / company)': 'చట్టబద్ధ స్థితి (ఏకైక / భాగస్వామ్యం / కంపెనీ)',
  'List of Existing Machinery': 'ఉన్న యంత్రాల జాబితా',
  'MSE-GIFT': 'MSE-GIFT',
  'MSE-SPICE': 'MSE-SPICE',
  'MSME Sustainable ZED': 'MSME సస్టైనబుల్ ZED',
  'Machinery / Capex Quotations': 'యంత్రాల / మూలధన కోటేషన్లు',
  'Machinery / equipment (₹ Lakhs)': 'యంత్రాలు / పరికరాలు (₹ లక్షలు)',
  'Machinery Quotations (tech specs)': 'యంత్రాల కోటేషన్లు (సాంకేతిక వివరాలు)',
  'Machinery Quotations / Invoices': 'యంత్రాల కోటేషన్లు / ఇన్‌వాయిస్‌లు',
  'Machinery order / installation': 'యంత్రాల ఆర్డర్ / స్థాపన',
  'Major competitors + your strengths / weaknesses': 'ప్రధాన పోటీదారులు + మీ బలాలు / బలహీనతలు',
  'Manufacturing / Product Licence': 'తయారీ / ఉత్పత్తి లైసెన్స్',
  'Manufacturing / Product Licence (if any)': 'తయారీ / ఉత్పత్తి లైసెన్స్ (ఉంటే)',
  'Margin money / subsidy %': 'మార్జిన్ మనీ / సబ్సిడీ %',
  'NHDP (handloom)': 'NHDP (హ్యాండ్‌లూమ్)',
  'National SC/ST Hub': 'జాతీయ SC/ST హబ్',
  'New Machinery Quotations / Invoices': 'కొత్త యంత్రాల కోటేషన్లు / ఇన్‌వాయిస్‌లు',
  'New P&M Quotations (second-hand ineligible)': 'కొత్త P&M కోటేషన్లు (వాడినవి అనర్హం)',
  'New tools needed': 'కావలసిన కొత్త పనిముట్లు',
  'Other subsidy / grant if converging (₹ Lakhs) — else 0':
    'కలిపి పొందే ఇతర సబ్సిడీ / గ్రాంట్ (₹ లక్షలు) — లేకపోతే 0',
  'Own / promoter contribution (₹ Lakhs)': 'స్వంత / ప్రమోటర్ వాటా (₹ లక్షలు)',
  'Own contribution %': 'స్వంత వాటా %',
  'Own contribution (₹ Lakhs)': 'స్వంత వాటా (₹ లక్షలు)',
  'Own contribution (₹ Lakhs) — 10% for all categories':
    'స్వంత వాటా (₹ లక్షలు) — అన్ని వర్గాలకు 10%',
  'Own contribution (₹ Lakhs) — typically 10% general / 5% special':
    'స్వంత వాటా (₹ లక్షలు) — సాధారణంగా సాధారణ 10% / ప్రత్యేక 5%',
  'Owner(s)': 'యజమాని(లు)',
  'PM Vishwakarma Certificate / ID (if issued)': 'PM విశ్వకర్మ సర్టిఫికేట్ / ID (జారీ అయితే)',
  'PMEGP 2nd-loan margin money (₹ Lakhs) — 15% / 20% NER-Hill':
    'PMEGP రెండవ రుణ మార్జిన్ మనీ (₹ లక్షలు) — 15% / NER-హిల్ 20%',
  'PMEGP margin money / subsidy (₹ Lakhs)': 'PMEGP మార్జిన్ మనీ / సబ్సిడీ (₹ లక్షలు)',
  'PMFME capital grant (₹ Lakhs) — 35%, cap ₹10 L':
    'PMFME మూలధన గ్రాంట్ (₹ లక్షలు) — 35%, పరిమితి ₹10 లక్షలు',
  'PMS (marketing / fair)': 'PMS (మార్కెటింగ్ / ప్రదర్శన)',
  'Photos of Existing Unit': 'ఉన్న యూనిట్ ఫోటోలు',
  'Plant & machinery (₹ Lakhs)': 'ప్లాంట్ మరియు యంత్రాలు (₹ లక్షలు)',
  'Pollution Consent': 'కాలుష్య అనుమతి',
  'Power connection': 'విద్యుత్ కనెక్షన్',
  'Power requirement': 'విద్యుత్ అవసరం',
  'Preliminary & pre-operative (₹ Lakhs)': 'ప్రాథమిక మరియు ప్రీ-ఆపరేటివ్ (₹ లక్షలు)',
  'Premises note (own / lease / rent)': 'ప్రాంగణ గమనిక (సొంత / లీజు / అద్దె)',
  'Present / proposed activity summary': 'ప్రస్తుత / ప్రతిపాదిత కార్యకలాప సారాంశం',
  'Previous Fair Photos (optional)': 'గత ప్రదర్శన ఫోటోలు (ఐచ్ఛికం)',
  'Previous Mudra Loan Repayment / Closure Certificate':
    'గత ముద్ర రుణ చెల్లింపు / ముగింపు సర్టిఫికేట్',
  'Prior PMEGP / REGP / MUDRA Sanction Letter': 'గత PMEGP / REGP / ముద్ర మంజూరు లేఖ',
  'Product List / Catalogue Draft': 'ఉత్పత్తి జాబితా / కేటలాగ్ డ్రాఫ్ట్',
  'Promoter contribution / equity (₹ Lakhs)': 'ప్రమోటర్ వాటా / ఈక్విటీ (₹ లక్షలు)',
  'Quotations / WC Evidence': 'కోటేషన్లు / WC రుజువు',
  'RAMP TEAM (ONDC)': 'RAMP TEAM (ONDC)',
  'Recent Energy Bill': 'ఇటీవలి విద్యుత్ బిల్లు',
  'Rural / Village Address Proof': 'గ్రామీణ / గ్రామ చిరునామా రుజువు',
  'SC / ST Caste Certificate': 'SC / ST కుల ధృవీకరణ పత్రం',
  'SC/ST / Women Category Proof (if claimed)': 'SC/ST / మహిళా వర్గం రుజువు (క్లెయిమ్ చేస్తే)',
  'SC/ST Ownership Proof (APIIC land-rebate claim)':
    'SC/ST యాజమాన్య రుజువు (APIIC భూమి రాయితీ క్లెయిమ్)',
  'SC/ST or women category': 'SC/ST లేదా మహిళా వర్గం',
  'SCLCSS (SC/ST only)': 'SCLCSS (SC/ST మాత్రమే)',
  'SCLCSS capital subsidy (₹ Lakhs) — 25%, cap ₹25 L':
    'SCLCSS మూలధన సబ్సిడీ (₹ లక్షలు) — 25%, పరిమితి ₹25 లక్షలు',
  'Savings Bank Passbook / Statement': 'సేవింగ్స్ బ్యాంకు పాస్‌బుక్ / స్టేట్‌మెంట్',
  'Sector / industry type': 'రంగం / పరిశ్రమ రకం',
  'Shipping / LC / Export Evidence': 'షిప్పింగ్ / LC / ఎగుమతి రుజువు',
  'Shop / shed / workplace': 'దుకాణం / షెడ్ / పని స్థలం',
  'Shop / shed / workplace name': 'దుకాణం / షెడ్ / పని స్థలం పేరు',
  'Shop Address Proof': 'దుకాణ చిరునామా రుజువు',
  'Short impact note': 'చిన్న ప్రభావ గమనిక',
  'Short intro — what the unit does': 'చిన్న పరిచయం — యూనిట్ ఏమి చేస్తుంది',
  'Single Desk Pollution Clearances (CFE/CFO)': 'సింగిల్ డెస్క్ కాలుష్య అనుమతులు (CFE/CFO)',
  'Special-category Ownership Proof (women / SC/ST / BC / PwD / etc.)':
    'ప్రత్యేక వర్గ యాజమాన్య రుజువు (మహిళ / SC/ST / BC / వికలాంగులు మొదలైనవి)',
  'Stand-Up India': 'స్టాండ్-అప్ ఇండియా',
  'Start / commencement': 'ప్రారంభం',
  'Start / commencement (existing or proposed)': 'ప్రారంభం (ఉన్నది లేదా ప్రతిపాదితం)',
  'Target customers / market': 'లక్ష్య కస్టమర్లు / మార్కెట్',
  'Term Loan Sanction (if credit-linked)': 'టర్మ్ లోన్ మంజూరు (క్రెడిట్-లింక్డ్ అయితే)',
  'Term Loan Sanction / In-principle': 'టర్మ్ లోన్ మంజూరు / సూత్రప్రాయం',
  'This is an individual entrepreneur unit (one firm), not a multi-unit CFC / SPV report.':
    'ఇది ఒక వ్యక్తిగత వ్యవస్థాపక యూనిట్ (ఒక సంస్థ), బహుళ యూనిట్ CFC / SPV నివేదిక కాదు.',
  'Toolkit List / Designated-centre Quote': 'టూల్‌కిట్ జాబితా / నిర్దేశిత కేంద్ర కోట్',
  'Toolkit e-voucher (₹ Lakhs) — usually 0.15': 'టూల్‌కిట్ ఈ-వౌచర్ (₹ లక్షలు) — సాధారణంగా 0.15',
  'Tools / process level': 'పనిముట్లు / ప్రక్రియ స్థాయి',
  'Trial run': 'ట్రయల్ రన్',
  'UPI ID': 'UPI ID',
  'UPI ID / QR Screenshot (linked to same account)':
    'UPI ID / QR స్క్రీన్‌షాట్ (అదే ఖాతాకు లింక్)',
  'Udyam Certificate (or application)': 'ఉద్యమ్ సర్టిఫికేట్ (లేదా దరఖాస్తు)',
  'Vanilla bank term loan (standard individual DPR)': 'సాధారణ బ్యాంకు టర్మ్ లోన్ (ప్రామాణిక వ్యక్తిగత DPR)',
  'Unit / Project Name': 'యూనిట్ / ప్రాజెక్ట్ పేరు',
  'Unit inside an APIIC park?': 'యూనిట్ APIIC పార్క్‌లో ఉందా?',
  'WC term loan tranche (₹ Lakhs)': 'WC టర్మ్ లోన్ విడత (₹ లక్షలు)',
  'Weaver ID / Handloom Corp Membership': 'నేత ID / హ్యాండ్‌లూమ్ కార్పొరేషన్ సభ్యత్వం',
  'White Rice Card': 'వైట్ రైస్ కార్డు',
  'Working capital (₹ Lakhs)': 'వర్కింగ్ క్యాపిటల్ (₹ లక్షలు)',
  'Year of establishment': 'స్థాపన సంవత్సరం',
  'Year-wise sales / costs / profit': 'సంవత్సరం వారీ అమ్మకాలు / ఖర్చులు / లాభం',
  'Heavy capex tables are hidden for Mudra Shishu / Kishore. Enter machinery and working-capital margin only.':
    'ముద్ర శిశు / కిషోర్‌కు పెద్ద మూలధన పట్టికలు దాచబడ్డాయి. యంత్రాలు మరియు వర్కింగ్ క్యాపిటల్ మార్జిన్ మాత్రమే నమోదు చేయండి.',
  'Assumed 7-year term at 12%. Average DSCR:':
    '7 సంవత్సరాల కాలం, 12% వడ్డీ అనుకోబడింది. సగటు DSCR:',
  ' — below 1.5; lenders may query this.': ' — 1.5 కంటే తక్కువ; రుణదాతలు దీన్ని అడగవచ్చు.',
  'uploaded successfully!': 'విజయవంతంగా అప్‌లోడ్ అయింది!',
  'form implementation in progress. Please check back soon.':
    'ఫారమ్ అమలు జరుగుతోంది. త్వరలో మళ్లీ చూడండి.',
};
