/** Auto-curated Telugu for scheme step titles (Step N: …). */
export const SCHEME_STEP_TITLES_TE: Record<string, string> = {
  'Step 1: Your unit – basic details': 'దశ 1: మీ యూనిట్ – ప్రాథమిక వివరాలు',
  'Step 2: Sector overview': 'దశ 2: రంగం అవలోకనం',
  'Step 3: District & location': 'దశ 3: జిల్లా & స్థలం',
  'Step 4: Your unit profile': 'దశ 4: మీ యూనిట్ ప్రొఫైల్',
  'Step 5: Value chain': 'దశ 5: విలువ గొలుసు',
  'Step 6: Market': 'దశ 6: మార్కెట్',
  'Step 7: Gaps': 'దశ 7: అంతరాలు',
  'Step 8: SWOT': 'దశ 8: SWOT',
  'Step 9: What you plan to do': 'దశ 9: మీరు చేయాలనుకుంటున్నది',
  'Step 10: Workplace / shed / unit': 'దశ 10: కార్యస్థలం / షెడ్ / యూనిట్',
  'Step 11: Applicant / firm': 'దశ 11: దరఖాస్తుదారు / సంస్థ',
  'Step 12: Project cost': 'దశ 12: ప్రాజెక్ట్ ఖర్చు',
  'Step 13: Means of finance': 'దశ 13: నిధుల సాధనాలు',
  'Step 14: Operating cost & sales': 'దశ 14: నిర్వహణ ఖర్చు & అమ్మకాలు',
  'Step 15: Financial viability': 'దశ 15: ఆర్థిక లాభదాయకత',
  'Step 16: Implementation schedule': 'దశ 16: అమలు షెడ్యూల్',
  'Step 17: Expected impact': 'దశ 17: ఆశించిన ప్రభావం',
  'Step 18: Document uploads': 'దశ 18: పత్రాల అప్‌లోడ్',
  'Step 1: Cover & entrepreneur': 'దశ 1: కవర్ & వ్యవస్థాపకుడు',
  'Step 2: Introduction & process': 'దశ 2: పరిచయం & ప్రక్రియ',
  'Step 2: Executive summary & process': 'దశ 2: కార్యనిర్వాహక సారాంశం & ప్రక్రియ',
  'Step 3: Location': 'దశ 3: స్థలం',
  'Step 4: Unit profile & capacity': 'దశ 4: యూనిట్ ప్రొఫైల్ & సామర్థ్యం',
  'Step 5: Market & sales assumptions': 'దశ 5: మార్కెట్ & అమ్మకాల అంచనాలు',
  'Step 6: Workshed / premises & power': 'దశ 6: వర్క్‌షెడ్ / ప్రాంగణం & విద్యుత్',
  'Step 7: Applicant / firm': 'దశ 7: దరఖాస్తుదారు / సంస్థ',
  'Step 8: Project cost': 'దశ 8: ప్రాజెక్ట్ ఖర్చు',
  'Step 9: Means of finance (critical)': 'దశ 9: నిధుల సాధనాలు (కీలకం)',
  'Step 10: Operating cost & sales': 'దశ 10: నిర్వహణ ఖర్చు & అమ్మకాలు',
  'Step 11: Financial viability': 'దశ 11: ఆర్థిక లాభదాయకత',
  'Step 12: Implementation schedule': 'దశ 12: అమలు షెడ్యూల్',
  'Step 13: Employment & impact': 'దశ 13: ఉపాధి & ప్రభావం',
  'Step 14: Documents & uploads': 'దశ 14: పత్రాలు & అప్‌లోడ్లు',
  'Step 1: Cover & category': 'దశ 1: కవర్ & వర్గం',
  'Step 2: Business activity': 'దశ 2: వ్యాపార కార్యకలాపం',
  'Step 4: Unit profile': 'దశ 4: యూనిట్ ప్రొఫైల్',
  'Step 6: Premises': 'దశ 6: ప్రాంగణం',
  'Step 9: Means of finance': 'దశ 9: నిధుల సాధనాలు',
  'Step 12: Documents & uploads': 'దశ 12: పత్రాలు & అప్‌లోడ్లు',
  'Step 1: Cover & eligibility': 'దశ 1: కవర్ & అర్హత',
  'Step 2: Business activity & process': 'దశ 2: వ్యాపార కార్యకలాపం & ప్రక్రియ',
  'Step 5: Market, buyers & competition': 'దశ 5: మార్కెట్, కొనుగోలుదారులు & పోటీ',
  'Step 13: Documents & uploads': 'దశ 13: పత్రాలు & అప్‌లోడ్లు',
  'Step 1: Cover & formalisation': 'దశ 1: కవర్ & అధికారికీకరణ',
  'Step 5: Market, buyers & raw material': 'దశ 5: మార్కెట్, కొనుగోలుదారులు & ముడి పదార్థం',
  'Step 6: Premises & utilities': 'దశ 6: ప్రాంగణం & యుటిలిటీలు',
  'Step 1: Cover & prior assistance': 'దశ 1: కవర్ & మునుపటి సహాయం',
  'Step 2: Introduction & upgrade process': 'దశ 2: పరిచయం & అప్‌గ్రేడ్ ప్రక్రియ',
  'Step 4: Unit profile & capacity (existing → proposed)': 'దశ 4: యూనిట్ ప్రొఫైల్ & సామర్థ్యం (ప్రస్తుత → ప్రతిపాదిత)',
  'Step 8: Upgrade project cost': 'దశ 8: అప్‌గ్రేడ్ ప్రాజెక్ట్ ఖర్చు',
  'Step 1: Cover & SC/ST eligibility': 'దశ 1: కవర్ & SC/ST అర్హత',
  'Step 2: Technology upgrade story': 'దశ 2: సాంకేతిక అప్‌గ్రేడ్ కథనం',
  'Step 5: Market & offtake': 'దశ 5: మార్కెట్ & అమ్మకాలు',
  'Step 8: Project cost (machinery-led)': 'దశ 8: ప్రాజెక్ట్ ఖర్చు (యంత్రాల నాయకత్వం)',
  'Step 1: Cover & AP eligibility': 'దశ 1: కవర్ & AP అర్హత',
  'Step 8: Upgrade project cost (FCI)': 'దశ 8: అప్‌గ్రేడ్ ప్రాజెక్ట్ ఖర్చు (FCI)',
  'Step 8: Project cost (FCI)': 'దశ 8: ప్రాజెక్ట్ ఖర్చు (FCI)',
  'Step 1: Cover & craft eligibility': 'దశ 1: కవర్ & వృత్తి అర్హత',
  'Step 2: Trade story & process': 'దశ 2: వృత్తి కథనం & ప్రక్రియ',
  'Step 4: Craft profile': 'దశ 4: వృత్తి ప్రొఫైల్',
  'Step 6: Workplace / premises': 'దశ 6: కార్యస్థలం / ప్రాంగణం',
  'Step 8: Project cost (tools + WC)': 'దశ 8: ప్రాజెక్ట్ ఖర్చు (పనిముట్లు + WC)',
  'Step 1: Cover & vending eligibility': 'దశ 1: కవర్ & విక్రయ అర్హత',
  'Step 2: Vending activity': 'దశ 2: విక్రయ కార్యకలాపం',
  'Step 3: Location / pitch': 'దశ 3: స్థలం / పిచ్',
  'Step 4: Vendor profile': 'దశ 4: విక్రేత ప్రొఫైల్',
  'Step 5: Market & daily sales': 'దశ 5: మార్కెట్ & రోజువారీ అమ్మకాలు',
  'Step 6: Pitch / workplace': 'దశ 6: పిచ్ / కార్యస్థలం',
  'Step 7: Applicant': 'దశ 7: దరఖాస్తుదారు',
  'Step 8: Working capital need': 'దశ 8: వర్కింగ్ క్యాపిటల్ అవసరం',
  'Step 10: Documents & uploads': 'దశ 10: పత్రాలు & అప్‌లోడ్లు',
  'Step 1: Cover & existing facility': 'దశ 1: కవర్ & ప్రస్తుత సౌకర్యం',
  'Step 2: Unit profile': 'దశ 2: యూనిట్ ప్రొఫైల్',
  'Step 3: Applicant / firm': 'దశ 3: దరఖాస్తుదారు / సంస్థ',
  'Step 4: Additional WC need': 'దశ 4: అదనపు WC అవసరం',
  'Step 5: Means of finance': 'దశ 5: నిధుల సాధనాలు',
  'Step 6: Operating cost & sales': 'దశ 6: నిర్వహణ ఖర్చు & అమ్మకాలు',
  'Step 7: Documents & uploads': 'దశ 7: పత్రాలు & అప్‌లోడ్లు',
  'Step 1: Cover & ZED levels': 'దశ 1: కవర్ & ZED స్థాయిలు',
  'Step 3: Quality / market need': 'దశ 3: నాణ్యత / మార్కెట్ అవసరం',
  'Step 4: Applicant / firm': 'దశ 4: దరఖాస్తుదారు / సంస్థ',
  'Step 5: Documents & uploads': 'దశ 5: పత్రాలు & అప్‌లోడ్లు',
  'Step 1: Cover & bottleneck': 'దశ 1: కవర్ & అడ్డంకి',
  'Step 2: Unit / shop-floor profile': 'దశ 2: యూనిట్ / షాప్-ఫ్లోర్ ప్రొఫైల్',
  'Step 3: Process / market need': 'దశ 3: ప్రక్రియ / మార్కెట్ అవసరం',
  'Step 1: Cover & IP type': 'దశ 1: కవర్ & IP రకం',
  'Step 2: Unit / invention profile': 'దశ 2: యూనిట్ / ఆవిష్కరణ ప్రొఫైల్',
  'Step 3: IP / market need': 'దశ 3: IP / మార్కెట్ అవసరం',
  'Step 1: Cover & fair details': 'దశ 1: కవర్ & ఫెయిర్ వివరాలు',
  'Step 2: Unit / product profile': 'దశ 2: యూనిట్ / ఉత్పత్తి ప్రొఫైల్',
  'Step 3: Market / fair offtake': 'దశ 3: మార్కెట్ / ఫెయిర్ అమ్మకాలు',
  'Step 1: Cover & GeM readiness': 'దశ 1: కవర్ & GeM సిద్ధత',
  'Step 3: Procurement focus': 'దశ 3: సేకరణ దృష్టి',
  'Step 1: Cover & incubator': 'దశ 1: కవర్ & ఇన్క్యూబేటర్',
  'Step 2: Innovation / livelihood story': 'దశ 2: ఆవిష్కరణ / జీవనోపాధి కథనం',
  'Step 4: Unit / livelihood profile': 'దశ 4: యూనిట్ / జీవనోపాధి ప్రొఫైల్',
  'Step 8: Light project cost': 'దశ 8: తేలికపాటి ప్రాజెక్ట్ ఖర్చు',
  'Step 1: Cover & loom eligibility': 'దశ 1: కవర్ & మగ్గం అర్హత',
  'Step 2: Handloom / process story': 'దశ 2: చేనేత / ప్రక్రియ కథనం',
  'Step 4: Weaver profile': 'దశ 4: నేత కార్మికుడి ప్రొఫైల్',
  'Step 6: Workplace / loom shed': 'దశ 6: కార్యస్థలం / మగ్గం షెడ్',
  'Step 8: Tools / WC cost': 'దశ 8: పనిముట్లు / WC ఖర్చు',
  'Step 2: Business / activity story': 'దశ 2: వ్యాపారం / కార్యకలాప కథనం',
  'Step 5: Market & sales': 'దశ 5: మార్కెట్ & అమ్మకాలు',
  'Step 2: Upgrade / process story': 'దశ 2: అప్‌గ్రేడ్ / ప్రక్రియ కథనం',
  'Step 1: Cover & scheme inputs': 'దశ 1: కవర్ & పథక ఇన్‌పుట్లు',
  'Step 3: Market / need': 'దశ 3: మార్కెట్ / అవసరం',
  'Step 2: Activity story': 'దశ 2: కార్యకలాప కథనం',
  'Step 8: Project / land cost': 'దశ 8: ప్రాజెక్ట్ / భూమి ఖర్చు',
  'Step 2: Unit / export profile': 'దశ 2: యూనిట్ / ఎగుమతి ప్రొఫైల్',
  'Step 4: Export credit / WC need': 'దశ 4: ఎగుమతి క్రెడిట్ / WC అవసరం',
  'Step 6: Operating & export sales': 'దశ 6: నిర్వహణ & ఎగుమతి అమ్మకాలు',
};

