/** Telugu strings for Create New Latest DPR scheme Step-1 (yellow) panels + option labels. */
export const SCHEME_FORM_TE: Record<string, string> = {
  '1st tranche — up to ₹15,000 (12 months)': '1వ విడత — ₹15,000 వరకు (12 నెలలు)',
  '2nd tranche — up to ₹25,000 (18 months)': '2వ విడత — ₹25,000 వరకు (18 నెలలు)',
  '3rd tranche — up to ₹50,000 (36 months)': '3వ విడత — ₹50,000 వరకు (36 నెలలు)',
  '8th class pass or higher': '8వ తరగతి లేదా అంతకంటే ఎక్కువ',
  'Above 10 and up to 100': '10 పైన 100 వరకు',
  'Account status': 'ఖాతా స్థితి',
  'Activity': 'కార్యకలాపం',
  'Activity / trade': 'కార్యకలాపం / వృత్తి',
  'Activity band': 'కార్యకలాప బ్యాండ్',
  'Additional ECLGS WC sought (₹ Lakhs)': 'అదనపు ECLGS WC కోరుకున్నది (₹ లక్షలు)',
  'Advanced training completed': 'ఉన్నత శిక్షణ పూర్తి',
  'Age': 'వయసు',
  'Age (≥ 18)': 'వయసు (≥ 18)',
  'Already filed': 'ఇప్పటికే దాఖలు',
  'Already have FSSAI': 'FSSAI ఇప్పటికే ఉంది',
  'AP CMEP — credit-linked': 'AP CMEP — క్రెడిట్-లింక్డ్',
  'AP domicile': 'AP నివాసం',
  'AP domicile confirmed?': 'AP నివాసం నిర్ధారించబడిందా?',
  'AP EDP capital subsidy on new-unit FCI — mutually exclusive with tech-upgrade; total incentives ≤ 75% FCI. Indicative': 'కొత్త-యూనిట్ FCIపై AP EDP క్యాపిటల్ సబ్సిడీ — టెక్-అప్‌గ్రేడ్‌తో విరుద్ధం; మొత్తం ≤ 75% FCI. సూచన',
  'AP FPP 4.0 — food processing': 'AP FPP 4.0 — ఆహార ప్రాసెసింగ్',
  'AP MSME-EDP 4.0 — new-unit eligibility': 'AP MSME-EDP 4.0 — కొత్త-యూనిట్ అర్హత',
  'AP MSME-PARKS — land rebate': 'AP MSME-PARKS — భూమి రాయితీ',
  'AP tech-upgrade subsidy on upgrade FCI — mutually exclusive with new-unit EDP capital subsidy; total incentives ≤ 75% FCI. Indicative': 'అప్‌గ్రేడ్ FCIపై AP టెక్-అప్‌గ్రేడ్ సబ్సిడీ — కొత్త-యూనిట్ EDP క్యాపిటల్ సబ్సిడీతో విరుద్ధం; మొత్తం ప్రోత్సాహకాలు ≤ 75% FCI. సూచన',
  'AP Technology Upgradation — eligibility': 'AP టెక్నాలజీ అప్‌గ్రేడేషన్ — అర్హత',
  'APIIC / industrial park': 'APIIC / పారిశ్రామిక పార్క్',
  'APIIC / park name': 'APIIC / పార్క్ పేరు',
  'APIIC land rebate': 'APIIC భూమి రాయితీ',
  'Application in progress': 'దరఖాస్తు జరుగుతోంది',
  'Approx daily sales (₹)': 'సుమారు రోజువారీ అమ్మకాలు (₹)',
  'Area (rural / urban)': 'ప్రాంతం (గ్రామీణ / పట్టణ)',
  'ASPIRE — incubator & livelihood': 'ASPIRE — ఇన్క్యుబేటర్ & జీవనోపాధి',
  'Authorised signatory': 'అధికార సంతకం చేసేవారు',
  'Bank checklist — competitors and how you win': 'బ్యాంకు చెక్‌లిస్ట్ — పోటీదారులు మరియు మీరు ఎలా గెలుస్తారు',
  'Basic training completed': 'ప్రాథమిక శిక్షణ పూర్తి',
  'BC Corporation': 'BC కార్పొరేషన్',
  'Below 8th class': '8వ తరగతి కంటే తక్కువ',
  'Booster category': 'బూస్టర్ వర్గం',
  'Both': 'రెండూ',
  'Both / allied': 'రెండూ / అనుబంధం',
  'Both pre + post': 'ప్రీ + పోస్ట్ రెండూ',
  'Bronze': 'బ్రాంజ్',
  'Business / Service / Trading (ceiling ₹25 lakh)': 'వ్యాపారం / సేవ / వ్యాపారం (పైపరిధి ₹25 లక్షలు)',
  'cap': 'పైపరిధి',
  'Capacity utilisation Year 1 (%)': 'సామర్థ్య వినియోగం సంవత్సరం 1 (%)',
  'capped at': 'పైపరిధి',
  'Catalogue SKUs (approx)': 'కేటలాగ్ SKUలు (సుమారు)',
  'Category': 'వర్గం',
  'Certificate of Vending / Vendor ID (ULB / TVC)': 'వెండింగ్ సర్టిఫికేట్ / విక్రేత ID (ULB / TVC)',
  'CGTMSE is a bank-side guarantee (MUDRA-adjacent) — governmentGrant usually 0. Own + bank = project cost. Women-owned may get higher cover %.': 'CGTMSE బ్యాంకు-వైపు గ్యారెంటీ (ముద్ర-సమానం) — governmentGrant సాధారణంగా 0. స్వంతం + బ్యాంకు = ప్రాజెక్ట్ ఖర్చు. మహిళా యాజమాన్యానికి అధిక కవర్ % రావచ్చు.',
  'CGTMSE — credit guarantee (MUDRA-adjacent)': 'CGTMSE — క్రెడిట్ గ్యారెంటీ (ముద్ర-సమానం)',
  'Circular sector': 'సర్క్యులర్ రంగం',
  'Coir Board status': 'కొయిర్ బోర్డు స్థితి',
  'Coir product line': 'కొయిర్ ఉత్పత్తి లైన్',
  'Composite (term + WC)': 'కాంపోజిట్ (టర్మ్ + WC)',
  'Composite loan sought (₹ Lakhs)': 'కావాల్సిన కాంపోజిట్ రుణం (₹ లక్షలు)',
  'Connectivity': 'కనెక్టివిటీ',
  'Controlling stake % (if not sole prop)': 'నియంత్రణ వాటా % (సోల్ ప్రాప్ కాకపోతే)',
  'Craft / trade (18 notified)': 'వృత్తి / కళ (18 నోటిఫైడ్)',
  'Credit-linked grant': 'క్రెడిట్-లింక్డ్ గ్రాంట్',
  'Current ZED level': 'ప్రస్తుత ZED స్థాయి',
  'CVY — coir unit': 'CVY — కొయిర్ యూనిట్',
  'Design': 'డిజైన్',
  'DIC': 'DIC',
  'E-waste': 'ఈ-వేస్ట్',
  'e.g. 12': 'ఉదా: 12',
  'e.g. 2019': 'ఉదా: 2019',
  'e.g. 2500': 'ఉదా: 2500',
  'e.g. 28': 'ఉదా: 28',
  'e.g. 3': 'ఉదా: 3',
  'e.g. 32': 'ఉదా: 32',
  'e.g. 35': 'ఉదా: 35',
  'e.g. 38': 'ఉదా: 38',
  'e.g. 40': 'ఉదా: 40',
  'e.g. 45': 'ఉదా: 45',
  'e.g. 5': 'ఉదా: 5',
  'e.g. 50': 'ఉదా: 50',
  'e.g. 500 sq.yd': 'ఉదా: 500 చ.గజాలు',
  'e.g. 55': 'ఉదా: 55',
  'e.g. 6': 'ఉదా: 6',
  'e.g. 60 (NIFTEM models ramp 60→70→80)': 'ఉదా: 60 (NIFTEM మోడల్స్ 60→70→80)',
  'e.g. 8': 'ఉదా: 8',
  'e.g. 9 sqm': 'ఉదా: 9 చ.మీ',
  'e.g. changeover time, scrap, inventory': 'ఉదా: మార్పిడి సమయం, స్క్రాప్, ఇన్వెంటరీ',
  'e.g. coir fibre, pith, mats': 'ఉదా: కొయిర్ ఫైబర్, పిత్, మ్యాట్స్',
  'e.g. vendor@upi': 'ఉదా: vendor@upi',
  'Early exploration': 'ప్రారంభ అన్వేషణ',
  'ECLGS 5.0 — existing WC facility': 'ECLGS 5.0 — ఉన్న WC సౌకర్యం',
  'ECLGS is a guaranteed WCTL — governmentGrant usually 0. Bank loan ≈ additional WC sought. Indicative 20% of peak': 'ECLGS హామీ ఉన్న WCTL — governmentGrant సాధారణంగా 0. బ్యాంకు రుణం ≈ అదనపు WC. సూచన గరిష్టంలో 20%',
  'Education': 'విద్య',
  'EE equipment focus': 'EE పరికరాల దృష్టి',
  'Eligible category': 'అర్హ వర్గం',
  'Energy baseline (kWh / month)': 'ఎనర్జీ బేస్‌లైన్ (kWh / నెల)',
  'Enterprise loan tranche': 'ఎంటర్‌ప్రైజ్ రుణ విడత',
  'Enterprise size': 'ఎంటర్‌ప్రైజ్ పరిమాణం',
  'Entrepreneur age': 'వ్యవస్థాపకుని వయసు',
  'Entrepreneur full name': 'వ్యవస్థాపకుని పూర్తి పేరు',
  'Entrepreneur name': 'వ్యవస్థాపకుని పేరు',
  'EPM Niryat is 2.75% interest subvention on eligible export credit — not a capital grant. Keep governmentGrant at 0; bank loan ≈ export credit sought.': 'EPM నిర్యాత్ అర్హ ఎగుమతి క్రెడిట్‌పై 2.75% వడ్డీ సబ్వెన్షన్ — క్యాపిటల్ గ్రాంట్ కాదు. governmentGrant 0 ఉంచండి; బ్యాంకు రుణం ≈ ఎగుమతి క్రెడిట్.',
  'EPM Niryat — export credit': 'EPM నిర్యాత్ — ఎగుమతి క్రెడిట్',
  'Estimated fair cost (₹ Lakhs)': 'అంచనా ఫేర్ ఖర్చు (₹ లక్షలు)',
  'Event / fair name': 'ఈవెంట్ / ఫేర్ పేరు',
  'Ex-serviceman': 'మాజీ సైనికుడు',
  'Existing annual turnover (₹ Lakhs)': 'ప్రస్తుత వార్షిక టర్నోవర్ (₹ లక్షలు)',
  'Existing capacity (before upgrade)': 'ప్రస్తుత సామర్థ్యం (అప్‌గ్రేడ్ ముందు)',
  'Existing fund-based WC limit (₹ Lakhs)': 'ఉన్న ఫండ్-బేస్డ్ WC పరిమితి (₹ లక్షలు)',
  'Existing MSE — tech upgrade / expansion': 'ఉన్న MSE — టెక్ అప్‌గ్రేడ్ / విస్తరణ',
  'Existing tech': 'ప్రస్తుత టెక్',
  'Existing technology': 'ప్రస్తుత సాంకేతికత',
  'Existing unit years': 'ఉన్న యూనిట్ సంవత్సరాలు',
  'Existing unit — upgrade / expansion': 'ఉన్న యూనిట్ — అప్‌గ్రేడ్ / విస్తరణ',
  'Expect ≥ 3': '≥ 3 ఆశించండి',
  'Expected lean gain': 'ఆశించిన లీన్ లాభం',
  'Expected productivity / quality / cost gain': 'ఆశించిన ఉత్పాదకత / నాణ్యత / ఖర్చు లాభం',
  'Expected saving (%)': 'ఆశించిన ఆదా (%)',
  'Experience in this line (years)': 'ఈ రంగంలో అనుభవం (సంవత్సరాలు)',
  'Export credit sought (₹ Lakhs)': 'కోరిన ఎగుమతి క్రెడిట్ (₹ లక్షలు)',
  'Export markets': 'ఎగుమతి మార్కెట్లు',
  'Fair city': 'ఫేర్ నగరం',
  'Farmers / mandi / contract sourcing — MoFPI DPR requirement': 'రైతులు / మండి / కాంట్రాక్ట్ సోర్సింగ్ — MoFPI DPR అవసరం',
  'Filing stage': 'దాఖలు దశ',
  'Fill Nature of Business and Major Products first, then suggest a title': 'ముందు వ్యాపార స్వభావం మరియు ప్రధాన ఉత్పత్తులు నింపి, తర్వాత శీర్షిక సూచించండి',
  'First loan repaid in time?': 'మొదటి రుణం సమయానికి తీర్చారా?',
  'First margin money adjusted?': 'మొదటి మార్జిన్ మనీ సర్దుబాటు అయిందా?',
  'First sanction / project cost (₹ Lakhs)': 'మొదటి మంజూరు / ప్రాజెక్ట్ ఖర్చు (₹ లక్షలు)',
  'First tranche (up to ₹1 lakh)': '1వ విడత (₹1 లక్ష వరకు)',
  'Fixed stall / kiosk': 'స్థిర స్టాల్ / కియోస్క్',
  'Focus': 'దృష్టి',
  'Food processing / value-addition steps (as in NIFTEM model DPRs)': 'ఆహార ప్రాసెసింగ్ / విలువ జోడింపు దశలు (NIFTEM మోడల్ DPRల మాదిరి)',
  'Footpath / pavement pitch': 'ఫుట్‌పాత్ / పావ్‌మెంట్ స్థలం',
  'Formalisation / local offtake / farmer linkage — short note': 'అధికారికీకరణ / స్థానిక అమ్మకం / రైతు అనుసంధానం — చిన్న నోట్',
  'Formulation / pharma product': 'ఫార్ములేషన్ / ఫార్మా ఉత్పత్తి',
  'FPO / SHG': 'FPO / SHG',
  'Frame loom': 'ఫ్రేమ్ మగ్గం',
  'FSSAI': 'FSSAI',
  'Full correspondence address for KYC': 'KYC కోసం పూర్తి ఉత్తరాది చిరునామా',
  'Full name as in Aadhaar': 'ఆధార్‌లో ఉన్న పూర్తి పేరు',
  'GeM experience': 'GeM అనుభవం',
  'GeM registered': 'GeM నమోదు',
  'general': 'సాధారణం',
  'General (no booster)': 'సాధారణం (బూస్టర్ లేదు)',
  'General category': 'సాధారణ వర్గం',
  'General rebate': 'సాధారణ రాయితీ',
  'Geographical Indication (GI)': 'భౌగోళిక సూచన (GI)',
  'GMP status': 'GMP స్థితి',
  'Gold': 'గోల్డ్',
  'Granted / registered': 'మంజూరు / నమోదు',
  'Hard': 'హార్డ్',
  'Have bid on GeM': 'GeMపై బిడ్ చేశారు',
  'Have won GeM orders': 'GeM ఆర్డర్లు గెలిచారు',
  'Hawking / door-to-door': 'హాకింగ్ / ఇంటింటికి',
  'Home / household workplace': 'ఇల్లు / గృహ కార్యస్థలం',
  'Home / village workplace': 'ఇల్లు / గ్రామ కార్యస్థలం',
  'Home loom shed': 'ఇంటి మగ్గం షెడ్',
  'Home-based coir unit': 'ఇంటి-ఆధారిత కొయిర్ యూనిట్',
  'How you make / deliver the craft product or service (step by step)': 'మీరు క్రాఫ్ట్ ఉత్పత్తి / సేవను ఎలా తయారు చేస్తారు (దశలవారీగా)',
  'How you source, prepare (if food), and sell — daily routine': 'మీరు ఎలా సేకరించి, తయారు చేసి (ఆహారమైతే), అమ్ముతారు — రోజువారీ రొటీన్',
  'HSN lines': 'HSN లైన్లు',
  'Idea / prior art search': 'ఆలోచన / మునుపటి కళ శోధన',
  'Implementing agency': 'అమలు ఏజెన్సీ',
  'Incubator / LBI name': 'ఇన్క్యుబేటర్ / LBI పేరు',
  'Incubator / LBI space': 'ఇన్క్యుబేటర్ / LBI స్థలం',
  'Indicative capital subsidy': 'సూచన క్యాపిటల్ సబ్సిడీ',
  'Indicative grant for current project cost fields': 'ప్రస్తుత ప్రాజెక్ట్ ఖర్చు ఫీల్డ్‌లకు సూచన గ్రాంట్',
  'Indicative margin money': 'సూచన మార్జిన్ మనీ',
  'Indicative quantum': 'సూచన పరిమాణం',
  'Indicative support': 'సూచన మద్దతు',
  'Indicative tech-upgrade subsidy': 'సూచన టెక్-అప్‌గ్రేడ్ సబ్సిడీ',
  'Indicative upgrade MM': 'సూచన అప్‌గ్రేడ్ MM',
  'Indicative WC loan': 'సూచన WC రుణం',
  'Indirect employment (count)': 'పరోక్ష ఉపాధి (సంఖ్య)',
  'Innovation / livelihood brief': 'ఆవిష్కరణ / జీవనోపాధి సంక్షిప్తం',
  'interest': 'వడ్డీ',
  'interest subsidy': 'వడ్డీ సబ్సిడీ',
  'interest subsidy (quarterly, not capital grant)': 'వడ్డీ సబ్సిడీ (త్రైమాసికం, క్యాపిటల్ గ్రాంట్ కాదు)',
  'Invention / mark title': 'ఆవిష్కరణ / మార్క్ శీర్షిక',
  'IP type': 'IP రకం',
  'Jacquard / semi-automatic': 'జాకార్డ్ / సెమీ-ఆటోమేటిక్',
  'Kapu Corporation': 'కాపు కార్పొరేషన్',
  'Keep light — employment / local benefit in one short note': 'సంక్షిప్తంగా — ఉపాధి / స్థానిక ప్రయోజనం ఒక చిన్న నోట్‌లో',
  'Kishore (above ₹50,000 to ₹5 lakh)': 'కిషోర్ (₹50,000 పైన ₹5 లక్షల వరకు)',
  'Knowledge / service enterprise': 'నాలెడ్జ్ / సేవా ఎంటర్‌ప్రైజ్',
  'KVIC': 'KVIC',
  'L': 'ల',
  'Land rebate claim': 'భూమి రాయితీ క్లెయిమ్',
  'Latest annual turnover (₹ Lakhs)': 'ఇటీవలి వార్షిక టర్నోవర్ (₹ లక్షలు)',
  'LEAN — process bottleneck': 'LEAN — ప్రాసెస్ అడ్డంకి',
  'Lease / rent': 'లీజు / అద్దె',
  'Leased': 'లీజు',
  'Leased / rented': 'లీజు / అద్దె',
  'Letter of Recommendation (portal digital only)': 'సిఫార్సు పత్రం (పోర్టల్ డిజిటల్ మాత్రమే)',
  'loan cap': 'రుణ పైపరిధి',
  'Loan purpose': 'రుణ ఉద్దేశం',
  'Loan tranche': 'రుణ విడత',
  'Loom type': 'మగ్గం రకం',
  'Machinery / process being added': 'జోడిస్తున్న యంత్రాలు / ప్రక్రియ',
  'Main process bottleneck': 'ప్రధాన ప్రాసెస్ అడ్డంకి',
  'Manufacturing': 'తయారీ',
  'Manufacturing (ceiling ₹1 crore)': 'తయారీ (పైపరిధి ₹1 కోటి)',
  'Medical device': 'మెడికల్ డివైస్',
  'Medium': 'మధ్య',
  'Micro': 'సూక్ష్మ',
  'Minority Corporation': 'మైనారిటీ కార్పొరేషన్',
  'Mobile cart / thela': 'మొబైల్ కార్ట్ / తేలా',
  'Modernisation / turnover growth from upgrade — short note': 'ఆధునీకరణ / అప్‌గ్రేడ్ నుండి టర్నోవర్ వృద్ధి — చిన్న నోట్',
  'months': 'నెలలు',
  'MSE-GIFT — green / EE': 'MSE-GIFT — గ్రీన్ / EE',
  'MSE-SPICE — circular economy': 'MSE-SPICE — సర్క్యులర్ ఎకానమీ',
  'MSE-SPICE: governmentGrant ≈ 25% of new P&M (cap ₹12.5 L). Second-hand machinery ineligible. Brownfield only.': 'MSE-SPICE: governmentGrant ≈ కొత్త P&Mలో 25% (పైపరిధి ₹12.5 ల). సెకండ్-హ్యాండ్ యంత్రాలు అనర్హం. బ్రౌన్‌ఫీల్డ్ మాత్రమే.',
  'MSME Innovative — IPR': 'MSME ఇన్నోవేటివ్ — IPR',
  'MUDRA': 'ముద్ర',
  'MUDRA is not a subsidy scheme. Own + bank (+ other) should equal total project cost. Category': 'ముద్ర సబ్సిడీ పథకం కాదు. స్వంతం + బ్యాంకు (+ ఇతరం) = మొత్తం ప్రాజెక్ట్ ఖర్చు. వర్గం',
  'MUDRA — PMMY category & applicant': 'ముద్ర — PMMY వర్గం & దరఖాస్తుదారు',
  'Must be 18 or older': '18 లేదా అంతకంటే ఎక్కువ ఉండాలి',
  'Must be ≥ 51 for firms': 'సంస్థలకు ≥ 51 ఉండాలి',
  'NER / Hill State?': 'NER / కొండ రాష్ట్రమా?',
  'New / upgraded P&M with tech specs (FCI base)': 'కొత్త / అప్‌గ్రేడ్ P&M టెక్ స్పెక్స్‌తో (FCI బేస్)',
  'New micro food processing unit': 'కొత్త సూక్ష్మ ఆహార ప్రాసెసింగ్ యూనిట్',
  'New P&M / equipment with tech specs (subsidy base)': 'కొత్త P&M / పరికరాలు టెక్ స్పెక్స్‌తో (సబ్సిడీ బేస్)',
  'New SC/ST MSE — first plant & machinery': 'కొత్త SC/ST MSE — మొదటి ప్లాంట్ & యంత్రాలు',
  'New tools needed (₹15,000 toolkit voucher)': 'కావాల్సిన కొత్త పనిముట్లు (₹15,000 టూల్‌కిట్ వోచర్)',
  'NHDP — loom & weaver': 'NHDP — మగ్గం & నేతగాడు',
  'No': 'కాదు',
  'No — eligible (no similar loan in last 5 years)': 'కాదు — అర్హం (గత 5 సం.లో ఇలాంటి రుణం లేదు)',
  'No — non-ODOP (still eligible)': 'కాదు — ODOP కాదు (ఇంకా అర్హం)',
  'None yet (toolkit / training first)': 'ఇంకా లేదు (ముందు టూల్‌కిట్ / శిక్షణ)',
  'Not certified yet': 'ఇంకా సర్టిఫై కాలేదు',
  'Not on GeM yet': 'ఇంకా GeMలో లేరు',
  'Not started / awaiting skill assessment': 'మొదలవలేదు / నైపుణ్య అంచనా కోసం వేచి',
  'Not yet GMP': 'ఇంకా GMP కాదు',
  'Not yet registered': 'ఇంకా నమోదు కాలేదు',
  'OBMMS — welfare self-employment': 'OBMMS — సంక్షేమ స్వయం ఉపాధి',
  'ODOP aligned?': 'ODOP అనుగుణమా?',
  'of FCI': 'FCIలో',
  'ONDC readiness': 'ONDC సిద్ధత',
  'Other': 'ఇతరం',
  'Other / not eligible': 'ఇతరం / అర్హం కాదు',
  'Other circular economy': 'ఇతర సర్క్యులర్ ఎకానమీ',
  'Other IP': 'ఇతర IP',
  'Other notified category': 'ఇతర నోటిఫైడ్ వర్గం',
  'Other welfare corp': 'ఇతర సంక్షేమ కార్ప్',
  'Own': 'స్వంతం',
  'Own + bank WC tranche (+ other) = total. Cap': 'స్వంతం + బ్యాంకు WC విడత (+ ఇతరం) = మొత్తం. పైపరిధి',
  'Own + margin money + bank (+ other) must equal total project cost. Indicative subsidy': 'స్వంతం + మార్జిన్ మనీ + బ్యాంకు (+ ఇతరం) = మొత్తం ప్రాజెక్ట్ ఖర్చు. సూచన సబ్సిడీ',
  'Own + toolkit voucher (usually 0.15 L) + enterprise loan tranche (+ other) = total. Interest': 'స్వంతం + టూల్‌కిట్ వోచర్ (సాధారణంగా 0.15 ల) + ఎంటర్‌ప్రైజ్ రుణ విడత (+ ఇతరం) = మొత్తం. వడ్డీ',
  'Own / lease / rent — how premises are held': 'స్వంతం / లీజు / అద్దె — ప్రాంగణం ఎలా ఉంది',
  'Own contribution': 'స్వంత వాటా',
  'Own contribution must be at least 10% of project cost. Own + bank (+ grant/other) = total. Category': 'స్వంత వాటా కనీసం 10% ఉండాలి. స్వంతం + బ్యాంకు (+ గ్రాంట్/ఇతరం) = మొత్తం. వర్గం',
  'Own land / building': 'స్వంత భూమి / భవనం',
  'Own shed / workshed': 'స్వంత షెడ్ / వర్క్‌షెడ్',
  'Own shop / workshed': 'స్వంత దుకాణం / వర్క్‌షెడ్',
  'Owned': 'స్వంతం',
  'Owner names, separated by commas': 'యజమానుల పేర్లు, కామాలతో వేరు',
  'Partial / upgrading to GMP': 'పాక్షికం / GMPకి అప్‌గ్రేడ్',
  'Patent': 'పేటెంట్',
  'Peak Q4 WC outstanding (₹ Lakhs)': 'Q4 గరిష్ట WC బకాయి (₹ లక్షలు)',
  'Pit loom': 'గుంత మగ్గం',
  'Planning catalogue / onboarding': 'కేటలాగ్ / ఆన్‌బోర్డింగ్ ప్రణాళిక',
  'Plastic recycling / circular': 'ప్లాస్టిక్ రీసైక్లింగ్ / సర్క్యులర్',
  'Plot area': 'ప్లాట్ వైశాల్యం',
  'PM SVANidhi — vending & eligibility': 'పీఎం స్వనిధి — విక్రయం & అర్హత',
  'PM Vishwakarma — craft & eligibility': 'పీఎం విశ్వకర్మ — వృత్తి & అర్హత',
  'PMEGP (1st loan)': 'PMEGP (1వ రుణం)',
  'PMEGP 2nd loan — prior assistance': 'PMEGP 2వ రుణం — మునుపటి సహాయం',
  'PMEGP — entrepreneur & subsidy inputs': 'PMEGP — వ్యవస్థాపకుడు & సబ్సిడీ ఇన్‌పుట్లు',
  'PMFME — formalisation & eligibility': 'PMFME — అధికారికీకరణ & అర్హత',
  'PMMY category': 'PMMY వర్గం',
  'PMPDS — promotion': 'PMPDS — ప్రచారం',
  'PMS — fair / marketing': 'PMS — ఫేర్ / మార్కెటింగ్',
  'Post-shipment': 'పోస్ట్-షిప్‌మెంట్',
  'Power requirement (HP / kW) — optional': 'విద్యుత్ అవసరం (HP / kW) — ఐచ్ఛికం',
  'Pre / post shipment': 'ప్రీ / పోస్ట్ షిప్‌మెంట్',
  'Pre-shipment': 'ప్రీ-షిప్‌మెంట్',
  'Premises': 'ప్రాంగణం',
  'Premises type': 'ప్రాంగణం రకం',
  'Premises — owned / rented': 'ప్రాంగణం — స్వంతం / అద్దె',
  'Present or proposed activity summary': 'ప్రస్తుత లేదా ప్రతిపాదిత కార్యకలాప సారాంశం',
  'Prior scheme': 'మునుపటి పథకం',
  'Process after new plant & machinery (manufacturing)': 'కొత్త ప్లాంట్ & యంత్రాల తర్వాత ప్రక్రియ',
  'Process after upgrade / modernisation': 'అప్‌గ్రేడ్ / ఆధునీకరణ తర్వాత ప్రక్రియ',
  'Process of manufacture': 'తయారీ ప్రక్రియ',
  'Process of manufacture / service delivery (bank checklist)': 'తయారీ / సేవా ప్రక్రియ (బ్యాంకు చెక్‌లిస్ట్)',
  'Process of manufacture for the new greenfield unit': 'కొత్త గ్రీన్‌ఫీల్డ్ యూనిట్ తయారీ ప్రక్రియ',
  'Procurement focus': 'సేకరణ దృష్టి',
  'Product licence': 'ఉత్పత్తి లైసెన్స్',
  'Product line': 'ఉత్పత్తి లైన్',
  'Product list note': 'ఉత్పత్తి జాబితా నోట్',
  'Promotion / development need': 'ప్రచారం / అభివృద్ధి అవసరం',
  'proposed': 'ప్రతిపాదిత',
  'Proposed limit (₹ Lakhs)': 'ప్రతిపాదిత పరిమితి (₹ లక్షలు)',
  'Proposed P&M cost (₹ Lakhs)': 'ప్రతిపాదిత P&M ఖర్చు (₹ లక్షలు)',
  'Proposed tech': 'ప్రతిపాదిత టెక్',
  'Proposed technology / upgrade': 'ప్రతిపాదిత సాంకేతికత / అప్‌గ్రేడ్',
  'Proposed workers (nos.)': 'ప్రతిపాదిత కార్మికులు (సంఖ్య)',
  'PTUAS — pharma upgrade': 'PTUAS — ఫార్మా అప్‌గ్రేడ్',
  'PwD': 'వికలాంగుడు',
  'Quality / sustainability focus': 'నాణ్యత / సుస్థిరత దృష్టి',
  'RAMP TEAM — ONDC': 'RAMP TEAM — ONDC',
  'Ready to onboard / already on ONDC': 'ఆన్‌బోర్డ్ సిద్ధం / ఇప్పటికే ONDCలో',
  'Registered with Coir Board': 'కొయిర్ బోర్డులో నమోదు',
  'REGP': 'REGP',
  'Rented': 'అద్దె',
  'Rented shed / shop': 'అద్దె షెడ్ / దుకాణం',
  'Rented shop / stall': 'అద్దె దుకాణం / స్టాల్',
  'Rented workplace': 'అద్దె కార్యస్థలం',
  'Rural': 'గ్రామీణ',
  'SC / ST category': 'SC / ST వర్గం',
  'SC / ST rebate': 'SC / ST రాయితీ',
  'SC Corporation': 'SC కార్పొరేషన్',
  'SC/ST controlling stake % (if not sole prop)': 'SC/ST నియంత్రణ వాటా % (సోల్ ప్రాప్ కాకపోతే)',
  'SC/ST Hub — procurement readiness': 'SC/ST హబ్ — సేకరణ సిద్ధత',
  'SC/ST wholly owned?': 'SC/ST పూర్తి యాజమాన్యమా?',
  'Scheduled Caste (SC)': 'షెడ్యూల్డ్ కులం (SC)',
  'Scheduled Tribe (ST)': 'షెడ్యూల్డ్ తెగ (ST)',
  'Scheme-specific details': 'పథక-సంబంధిత వివరాలు',
  'SCLCSS is 25% capital subsidy on eligible new P&M (cap ₹25 L), not PMEGP margin money. Indicative on machinery field': 'SCLCSS అర్హ కొత్త P&Mపై 25% క్యాపిటల్ సబ్సిడీ (పైపరిధి ₹25 ల), PMEGP మార్జిన్ మనీ కాదు. యంత్ర ఫీల్డ్‌పై సూచన',
  'SCLCSS — SC/ST capital subsidy': 'SCLCSS — SC/ST క్యాపిటల్ సబ్సిడీ',
  'Second tranche (up to ₹2 lakh)': '2వ విడత (₹2 లక్షల వరకు)',
  'Sector band': 'రంగం బ్యాండ్',
  'Select': 'ఎంచుకోండి',
  'Select agency': 'ఏజెన్సీ ఎంచుకోండి',
  'Select area': 'ప్రాంతం ఎంచుకోండి',
  'Select category': 'వర్గం ఎంచుకోండి',
  'Select education': 'విద్య ఎంచుకోండి',
  'Select purpose': 'ఉద్దేశం ఎంచుకోండి',
  'Selling price (₹ Lakhs)': 'అమ్మకపు ధర (₹ లక్షలు)',
  'Shishu (up to ₹50,000)': 'శిశు (₹50,000 వరకు)',
  'Shop or shed name / brief description': 'దుకాణం లేదా షెడ్ పేరు / చిన్న వివరణ',
  'Shop-floor size / lines': 'షాప్-ఫ్లోర్ పరిమాణం / లైన్లు',
  'Short cover name from Nature of Business + Major Products (not a full paragraph).': 'వ్యాపార స్వభావం + ప్రధాన ఉత్పత్తుల నుండి చిన్న కవర్ పేరు (పూర్తి పేరా కాదు).',
  'Short intro: product, customers, what the unit does': 'చిన్న పరిచయం: ఉత్పత్తి, కస్టమర్లు, యూనిట్ ఏమి చేస్తుంది',
  'Silver': 'సిల్వర్',
  'Similar self-employment loan in last 5 years?': 'గత 5 సంవత్సరాల్లో ఇలాంటి స్వయం ఉపాధి రుణం ఉందా?',
  'Site, roads, nearby markets — brief feasibility note': 'సైట్, రోడ్లు, సమీప మార్కెట్లు — చిన్న ఫీజిబిలిటీ నోట్',
  'SMA-1 (confirm with bank)': 'SMA-1 (బ్యాంకుతో నిర్ధారించండి)',
  'Small': 'చిన్న',
  'Soft': 'సాఫ్ట్',
  'Sole proprietorship / partnership / company': 'సోల్ ప్రొప్రైటర్‌షిప్ / భాగస్వామ్యం / కంపనీ',
  'Source': 'మూలం',
  'Sources of raw material': 'ముడి పదార్థాల మూలాలు',
  'Special category': 'ప్రత్యేక వర్గం',
  'Special category (SC / ST / OBC / Minority / Women / Ex-serviceman / PwD)': 'ప్రత్యేక వర్గం (SC / ST / OBC / మైనారిటీ / మహిళ / మాజీ సైనికుడు / వికలాంగుడు)',
  'Special category (wholly owned, AP domicile)?': 'ప్రత్యేక వర్గం (పూర్తి యాజమాన్యం, AP నివాసం)?',
  'Specification draft ready': 'స్పెసిఫికేషన్ డ్రాఫ్ట్ సిద్ధం',
  'ST Corporation': 'ST కార్పొరేషన్',
  'Stall size': 'స్టాల్ పరిమాణం',
  'Stand-Up India — eligibility': 'స్టాండ్-అప్ ఇండియా — అర్హత',
  'Standard (eligible)': 'స్టాండర్డ్ (అర్హం)',
  'State KVIB': 'రాష్ట్ర KVIB',
  'Step-by-step process (as in KVIC bakery / curd profiles)': 'దశలవారీ ప్రక్రియ (KVIC బేకరీ / పెరుగు ప్రొఫైల్‌ల మాదిరి)',
  'Suggest title': 'శీర్షిక సూచించు',
  'Target ZED level': 'లక్ష్య ZED స్థాయి',
  'Tarun (above ₹5 lakh to ₹10 lakh)': 'తరుణ్ (₹5 లక్షల పైన ₹10 లక్షల వరకు)',
  'Tarun Plus (above ₹10 lakh to ₹20 lakh)': 'తరుణ్ ప్లస్ (₹10 లక్షల పైన ₹20 లక్షల వరకు)',
  'Term loan (machinery / fixed assets)': 'టర్మ్ లోన్ (యంత్రాలు / స్థిర ఆస్తులు)',
  'Term loan (P&M / shed)': 'టర్మ్ లోన్ (P&M / షెడ్)',
  'Term loan + working capital': 'టర్మ్ లోన్ + వర్కింగ్ క్యాపిటల్',
  'Textile waste / circular fashion': 'టెక్స్‌టైల్ వ్యర్థం / సర్క్యులర్ ఫ్యాషన్',
  'These fields drive margin-money % (category × rural/urban). Spec: docs/schemes/PMEGP/pmegp.md': 'ఈ ఫీల్డ్‌లు మార్జిన్-మనీ % (వర్గం × గ్రామీణ/పట్టణ) నిర్ణయిస్తాయి.',
  'Title suggested': 'శీర్షిక సూచించబడింది',
  'toolkit': 'టూల్‌కిట్',
  'Tools to buy with the e-voucher at a designated centre': 'నియమిత కేంద్రంలో ఇ-వోచర్‌తో కొనాల్సిన పనిముట్లు',
  'Trademark': 'ట్రేడ్‌మార్క్',
  'Training stage': 'శిక్షణ దశ',
  'tranche cap': 'విడత పైపరిధి',
  'Transgender': 'ట్రాన్స్‌జెండర్',
  'Udyam number or “applied / ready”': 'ఉద్యమ్ నంబర్ లేదా “దరఖాస్తు / సిద్ధం”',
  'Udyam status / number': 'ఉద్యమ్ స్థితి / నంబర్',
  'Unit inside an APIIC park / estate?': 'యూనిట్ APIIC పార్క్ / ఎస్టేట్‌లో ఉందా?',
  'Unit stage': 'యూనిట్ దశ',
  'Upgrade MoF: own 10% + uniform MM 15% (20% NER/Hill) + bank. Not first-PMEGP category rates. Indicative MM': 'అప్‌గ్రేడ్ MoF: స్వంతం 10% + ఏకరూప MM 15% (20% NER/కొండ) + బ్యాంకు. మొదటి-PMEGP వర్గ రేట్లు కావు. సూచన MM',
  'UPI ID (linked to bank account) — mandatory': 'UPI ID (బ్యాంకు ఖాతాతో లింక్) — తప్పనిసరి',
  'Urban': 'పట్టణ',
  'Vending type / pitch': 'విక్రయ రకం / స్థలం',
  'Vendor full name': 'విక్రేత పూర్తి పేరు',
  'Weaver ID / corp membership': 'నేతగాడి ID / కార్ప్ సభ్యత్వం',
  'Weaver name': 'నేతగాడి పేరు',
  'Weavers’ colony / co-op shed': 'నేతగాళ్ల కాలనీ / సహకార షెడ్',
  'Weekly / municipal market': 'వారపు / మున్సిపల్ మార్కెట్',
  'Welfare corporation': 'సంక్షేమ కార్పొరేషన్',
  'What the unit uses today': 'యూనిట్ ఇప్పుడు వాడేది',
  'White rice card': 'వైట్ రైస్ కార్డు',
  'WHO-GMP / Schedule M compliant': 'WHO-GMP / షెడ్యూల్ M అనుగుణం',
  'Why additional liquidity is needed': 'అదనపు లిక్విడిటీ ఎందుకు కావాలి',
  'Why DIC should support this upgrade': 'DIC ఈ అప్‌గ్రేడ్‌ను ఎందుకు మద్దతు ఇవ్వాలి',
  'Will obtain / draft FSSAI': 'FSSAI తీసుకుంటాను / డ్రాఫ్ట్',
  'Woman entrepreneur': 'మహిళా వ్యవస్థాపకురాలు',
  'Women entrepreneur rebate': 'మహిళా వ్యవస్థాపకురాల రాయితీ',
  'Women-owned': 'మహిళా యాజమాన్యం',
  'women-owned': 'మహిళా యాజమాన్యం',
  'Working capital': 'వర్కింగ్ క్యాపిటల్',
  'Workplace': 'కార్యస్థలం',
  'Yarn source': 'నూలు మూలం',
  'Year of first subsidy': 'మొదటి సబ్సిడీ సంవత్సరం',
  'Years in operation': 'నిర్వహణ సంవత్సరాలు',
  'Years in street vending': 'వీధి విక్రయంలో సంవత్సరాలు',
  'Years of continuous profit': 'నిరంతర లాభ సంవత్సరాలు',
  'Years practising this craft': 'ఈ వృత్తిలో అనుభవ సంవత్సరాలు',
  'Yes': 'అవును',
  'Yes — district ODOP product': 'అవును — జిల్లా ODOP ఉత్పత్తి',
  'Yes — SC/ST micro/small may get land rebate': 'అవును — SC/ST సూక్ష్మ/చిన్నకు భూమి రాయితీ రావచ్చు',
  'Yes — similar loan taken (usually ineligible)': 'అవును — ఇలాంటి రుణం తీసుకున్నారు (సాధారణంగా అనర్హం)',
  'Yes — women-owned (higher cover %)': 'అవును — మహిళా యాజమాన్యం (అధిక కవర్ %)',
  'yrs': 'సం.',
  'ZED — certification levels': 'ZED — సర్టిఫికేషన్ స్థాయులు',
};

